/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockselect.h"

static const char* CMockString___exceptfds = "__exceptfds";
static const char* CMockString___nfds = "__nfds";
static const char* CMockString___readfds = "__readfds";
static const char* CMockString___sigmask = "__sigmask";
static const char* CMockString___timeout = "__timeout";
static const char* CMockString___writefds = "__writefds";
static const char* CMockString_pselect = "pselect";
static const char* CMockString_select = "select";

typedef struct _CMOCK_select_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  __BEGIN_DECLS int ReturnVal;
  int Expected___nfds;
  fd_set* __restrict Expected___readfds;
  fd_set* __restrict Expected___writefds;
  fd_set* __restrict Expected___exceptfds;
  struct timeval* __restrict Expected___timeout;
  int IgnoreArg___nfds;
  int IgnoreArg___readfds;
  int IgnoreArg___writefds;
  int IgnoreArg___exceptfds;
  int IgnoreArg___timeout;

} CMOCK_select_CALL_INSTANCE;

typedef struct _CMOCK_pselect_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  int ReturnVal;
  int Expected___nfds;
  fd_set* __restrict Expected___readfds;
  fd_set* __restrict Expected___writefds;
  fd_set* __restrict Expected___exceptfds;
  struct timespec* __restrict Expected___timeout;
  __sigset_t* __restrict Expected___sigmask;
  int IgnoreArg___nfds;
  int IgnoreArg___readfds;
  int IgnoreArg___writefds;
  int IgnoreArg___exceptfds;
  int IgnoreArg___timeout;
  int IgnoreArg___sigmask;

} CMOCK_pselect_CALL_INSTANCE;

static struct MockselectInstance
{
  int select_IgnoreBool;
  __BEGIN_DECLS int select_FinalReturn;
  CMOCK_select_CALLBACK select_CallbackFunctionPointer;
  int select_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE select_CallInstance;
  int pselect_IgnoreBool;
  int pselect_FinalReturn;
  CMOCK_pselect_CALLBACK pselect_CallbackFunctionPointer;
  int pselect_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE pselect_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockselect_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.select_IgnoreBool)
    Mock.select_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_select);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.select_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.select_CallbackFunctionPointer != NULL)
    Mock.select_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.pselect_IgnoreBool)
    Mock.pselect_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_pselect);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.pselect_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.pselect_CallbackFunctionPointer != NULL)
    Mock.pselect_CallInstance = CMOCK_GUTS_NONE;
}

void Mockselect_Init(void)
{
  Mockselect_Destroy();
}

void Mockselect_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.select_CallbackFunctionPointer = NULL;
  Mock.select_CallbackCalls = 0;
  Mock.pselect_CallbackFunctionPointer = NULL;
  Mock.pselect_CallbackCalls = 0;
}

__BEGIN_DECLS int select(int __nfds, fd_set* __restrict __readfds, fd_set* __restrict __writefds, fd_set* __restrict __exceptfds, struct timeval* __restrict __timeout)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_select_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_select);
  cmock_call_instance = (CMOCK_select_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.select_CallInstance);
  Mock.select_CallInstance = CMock_Guts_MemNext(Mock.select_CallInstance);
  if (Mock.select_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.select_FinalReturn;
    memcpy(&Mock.select_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(__BEGIN_DECLS int));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.select_CallbackFunctionPointer != NULL)
  {
    return Mock.select_CallbackFunctionPointer(__nfds, __readfds, __writefds, __exceptfds, __timeout, Mock.select_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg___nfds)
  {
    UNITY_SET_DETAILS(CMockString_select,CMockString___nfds);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected___nfds, __nfds, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___readfds)
  {
    UNITY_SET_DETAILS(CMockString_select,CMockString___readfds);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected___readfds), (void*)(&__readfds), sizeof(fd_set* __restrict), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___writefds)
  {
    UNITY_SET_DETAILS(CMockString_select,CMockString___writefds);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected___writefds), (void*)(&__writefds), sizeof(fd_set* __restrict), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___exceptfds)
  {
    UNITY_SET_DETAILS(CMockString_select,CMockString___exceptfds);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected___exceptfds), (void*)(&__exceptfds), sizeof(fd_set* __restrict), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___timeout)
  {
    UNITY_SET_DETAILS(CMockString_select,CMockString___timeout);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected___timeout), (void*)(&__timeout), sizeof(struct timeval* __restrict), cmock_line, CMockStringMismatch);
  }

  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_select(CMOCK_select_CALL_INSTANCE* cmock_call_instance, int __nfds, fd_set* __restrict __readfds, fd_set* __restrict __writefds, fd_set* __restrict __exceptfds, struct timeval* __restrict __timeout)
{
  cmock_call_instance->Expected___nfds = __nfds;
  cmock_call_instance->IgnoreArg___nfds = 0;
  cmock_call_instance->Expected___readfds = __readfds;
  cmock_call_instance->IgnoreArg___readfds = 0;
  cmock_call_instance->Expected___writefds = __writefds;
  cmock_call_instance->IgnoreArg___writefds = 0;
  cmock_call_instance->Expected___exceptfds = __exceptfds;
  cmock_call_instance->IgnoreArg___exceptfds = 0;
  cmock_call_instance->Expected___timeout = __timeout;
  cmock_call_instance->IgnoreArg___timeout = 0;
}

void select_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, __BEGIN_DECLS int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_select_CALL_INSTANCE));
  CMOCK_select_CALL_INSTANCE* cmock_call_instance = (CMOCK_select_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.select_CallInstance = CMock_Guts_MemChain(Mock.select_CallInstance, cmock_guts_index);
  Mock.select_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.select_IgnoreBool = (int)1;
}

void select_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, __BEGIN_DECLS int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_select_CALL_INSTANCE));
  CMOCK_select_CALL_INSTANCE* cmock_call_instance = (CMOCK_select_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.select_CallInstance = CMock_Guts_MemChain(Mock.select_CallInstance, cmock_guts_index);
  Mock.select_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void select_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int __nfds, fd_set* __restrict __readfds, fd_set* __restrict __writefds, fd_set* __restrict __exceptfds, struct timeval* __restrict __timeout, __BEGIN_DECLS int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_select_CALL_INSTANCE));
  CMOCK_select_CALL_INSTANCE* cmock_call_instance = (CMOCK_select_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.select_CallInstance = CMock_Guts_MemChain(Mock.select_CallInstance, cmock_guts_index);
  Mock.select_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_select(cmock_call_instance, __nfds, __readfds, __writefds, __exceptfds, __timeout);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(__BEGIN_DECLS int));
  UNITY_CLR_DETAILS();
}

void select_StubWithCallback(CMOCK_select_CALLBACK Callback)
{
  Mock.select_IgnoreBool = (int)0;
  Mock.select_CallbackFunctionPointer = Callback;
}

void select_CMockIgnoreArg___nfds(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_select_CALL_INSTANCE* cmock_call_instance = (CMOCK_select_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.select_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___nfds = 1;
}

void select_CMockIgnoreArg___readfds(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_select_CALL_INSTANCE* cmock_call_instance = (CMOCK_select_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.select_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___readfds = 1;
}

void select_CMockIgnoreArg___writefds(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_select_CALL_INSTANCE* cmock_call_instance = (CMOCK_select_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.select_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___writefds = 1;
}

void select_CMockIgnoreArg___exceptfds(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_select_CALL_INSTANCE* cmock_call_instance = (CMOCK_select_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.select_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___exceptfds = 1;
}

void select_CMockIgnoreArg___timeout(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_select_CALL_INSTANCE* cmock_call_instance = (CMOCK_select_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.select_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___timeout = 1;
}

int pselect(int __nfds, fd_set* __restrict __readfds, fd_set* __restrict __writefds, fd_set* __restrict __exceptfds, const struct timespec* __restrict __timeout, const __sigset_t* __restrict __sigmask)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_pselect_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_pselect);
  cmock_call_instance = (CMOCK_pselect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.pselect_CallInstance);
  Mock.pselect_CallInstance = CMock_Guts_MemNext(Mock.pselect_CallInstance);
  if (Mock.pselect_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.pselect_FinalReturn;
    Mock.pselect_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.pselect_CallbackFunctionPointer != NULL)
  {
    return Mock.pselect_CallbackFunctionPointer(__nfds, __readfds, __writefds, __exceptfds, __timeout, __sigmask, Mock.pselect_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg___nfds)
  {
    UNITY_SET_DETAILS(CMockString_pselect,CMockString___nfds);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected___nfds, __nfds, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___readfds)
  {
    UNITY_SET_DETAILS(CMockString_pselect,CMockString___readfds);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected___readfds), (void*)(&__readfds), sizeof(fd_set* __restrict), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___writefds)
  {
    UNITY_SET_DETAILS(CMockString_pselect,CMockString___writefds);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected___writefds), (void*)(&__writefds), sizeof(fd_set* __restrict), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___exceptfds)
  {
    UNITY_SET_DETAILS(CMockString_pselect,CMockString___exceptfds);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected___exceptfds), (void*)(&__exceptfds), sizeof(fd_set* __restrict), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___timeout)
  {
    UNITY_SET_DETAILS(CMockString_pselect,CMockString___timeout);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected___timeout), (void*)(&__timeout), sizeof(struct timespec* __restrict), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___sigmask)
  {
    UNITY_SET_DETAILS(CMockString_pselect,CMockString___sigmask);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected___sigmask), (void*)(&__sigmask), sizeof(__sigset_t* __restrict), cmock_line, CMockStringMismatch);
  }

  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_pselect(CMOCK_pselect_CALL_INSTANCE* cmock_call_instance, int __nfds, fd_set* __restrict __readfds, fd_set* __restrict __writefds, fd_set* __restrict __exceptfds, const struct timespec* __restrict __timeout, const __sigset_t* __restrict __sigmask)
{
  cmock_call_instance->Expected___nfds = __nfds;
  cmock_call_instance->IgnoreArg___nfds = 0;
  cmock_call_instance->Expected___readfds = __readfds;
  cmock_call_instance->IgnoreArg___readfds = 0;
  cmock_call_instance->Expected___writefds = __writefds;
  cmock_call_instance->IgnoreArg___writefds = 0;
  cmock_call_instance->Expected___exceptfds = __exceptfds;
  cmock_call_instance->IgnoreArg___exceptfds = 0;
  cmock_call_instance->Expected___timeout = (struct timespec* __restrict)__timeout;
  cmock_call_instance->IgnoreArg___timeout = 0;
  cmock_call_instance->Expected___sigmask = (__sigset_t* __restrict)__sigmask;
  cmock_call_instance->IgnoreArg___sigmask = 0;
}

void pselect_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_pselect_CALL_INSTANCE));
  CMOCK_pselect_CALL_INSTANCE* cmock_call_instance = (CMOCK_pselect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.pselect_CallInstance = CMock_Guts_MemChain(Mock.pselect_CallInstance, cmock_guts_index);
  Mock.pselect_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.pselect_IgnoreBool = (int)1;
}

void pselect_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_pselect_CALL_INSTANCE));
  CMOCK_pselect_CALL_INSTANCE* cmock_call_instance = (CMOCK_pselect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.pselect_CallInstance = CMock_Guts_MemChain(Mock.pselect_CallInstance, cmock_guts_index);
  Mock.pselect_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void pselect_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int __nfds, fd_set* __restrict __readfds, fd_set* __restrict __writefds, fd_set* __restrict __exceptfds, const struct timespec* __restrict __timeout, const __sigset_t* __restrict __sigmask, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_pselect_CALL_INSTANCE));
  CMOCK_pselect_CALL_INSTANCE* cmock_call_instance = (CMOCK_pselect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.pselect_CallInstance = CMock_Guts_MemChain(Mock.pselect_CallInstance, cmock_guts_index);
  Mock.pselect_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_pselect(cmock_call_instance, __nfds, __readfds, __writefds, __exceptfds, __timeout, __sigmask);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void pselect_StubWithCallback(CMOCK_pselect_CALLBACK Callback)
{
  Mock.pselect_IgnoreBool = (int)0;
  Mock.pselect_CallbackFunctionPointer = Callback;
}

void pselect_CMockIgnoreArg___nfds(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_pselect_CALL_INSTANCE* cmock_call_instance = (CMOCK_pselect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.pselect_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___nfds = 1;
}

void pselect_CMockIgnoreArg___readfds(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_pselect_CALL_INSTANCE* cmock_call_instance = (CMOCK_pselect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.pselect_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___readfds = 1;
}

void pselect_CMockIgnoreArg___writefds(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_pselect_CALL_INSTANCE* cmock_call_instance = (CMOCK_pselect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.pselect_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___writefds = 1;
}

void pselect_CMockIgnoreArg___exceptfds(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_pselect_CALL_INSTANCE* cmock_call_instance = (CMOCK_pselect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.pselect_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___exceptfds = 1;
}

void pselect_CMockIgnoreArg___timeout(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_pselect_CALL_INSTANCE* cmock_call_instance = (CMOCK_pselect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.pselect_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___timeout = 1;
}

void pselect_CMockIgnoreArg___sigmask(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_pselect_CALL_INSTANCE* cmock_call_instance = (CMOCK_pselect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.pselect_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___sigmask = 1;
}

