/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mocksocket.h"

static const char* CMockString___addr = "__addr";
static const char* CMockString___addr_len = "__addr_len";
static const char* CMockString___buf = "__buf";
static const char* CMockString___fd = "__fd";
static const char* CMockString___flags = "__flags";
static const char* CMockString___len = "__len";
static const char* CMockString___message = "__message";
static const char* CMockString___n = "__n";
static const char* CMockString___tmo = "__tmo";
static const char* CMockString___vlen = "__vlen";
static const char* CMockString___vmessages = "__vmessages";
static const char* CMockString_accept = "accept";
static const char* CMockString_accept4 = "accept4";
static const char* CMockString_connect = "connect";
static const char* CMockString_recv = "recv";
static const char* CMockString_recvfrom = "recvfrom";
static const char* CMockString_recvmmsg = "recvmmsg";
static const char* CMockString_recvmsg = "recvmsg";
static const char* CMockString_send = "send";
static const char* CMockString_sendmmsg = "sendmmsg";
static const char* CMockString_sendmsg = "sendmsg";
static const char* CMockString_sendto = "sendto";

typedef struct _CMOCK_connect_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  int ReturnVal;
  int Expected___fd;
  __CONST_SOCKADDR_ARG Expected___addr;
  socklen_t Expected___len;
  int IgnoreArg___fd;
  int IgnoreArg___addr;
  int IgnoreArg___len;

} CMOCK_connect_CALL_INSTANCE;

typedef struct _CMOCK_send_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  ssize_t ReturnVal;
  int Expected___fd;
  void* Expected___buf;
  size_t Expected___n;
  int Expected___flags;
  int IgnoreArg___fd;
  int IgnoreArg___buf;
  int IgnoreArg___n;
  int IgnoreArg___flags;

} CMOCK_send_CALL_INSTANCE;

typedef struct _CMOCK_recv_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  ssize_t ReturnVal;
  int Expected___fd;
  void* Expected___buf;
  size_t Expected___n;
  int Expected___flags;
  int IgnoreArg___fd;
  int IgnoreArg___buf;
  int IgnoreArg___n;
  int IgnoreArg___flags;

} CMOCK_recv_CALL_INSTANCE;

typedef struct _CMOCK_sendto_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  ssize_t ReturnVal;
  int Expected___fd;
  void* Expected___buf;
  size_t Expected___n;
  int Expected___flags;
  __CONST_SOCKADDR_ARG Expected___addr;
  socklen_t Expected___addr_len;
  int IgnoreArg___fd;
  int IgnoreArg___buf;
  int IgnoreArg___n;
  int IgnoreArg___flags;
  int IgnoreArg___addr;
  int IgnoreArg___addr_len;

} CMOCK_sendto_CALL_INSTANCE;

typedef struct _CMOCK_recvfrom_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  ssize_t ReturnVal;
  int Expected___fd;
  void* __restrict Expected___buf;
  size_t Expected___n;
  int Expected___flags;
  __SOCKADDR_ARG Expected___addr;
  socklen_t* __restrict Expected___addr_len;
  int IgnoreArg___fd;
  int IgnoreArg___buf;
  int IgnoreArg___n;
  int IgnoreArg___flags;
  int IgnoreArg___addr;
  int IgnoreArg___addr_len;

} CMOCK_recvfrom_CALL_INSTANCE;

typedef struct _CMOCK_sendmsg_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  ssize_t ReturnVal;
  int Expected___fd;
  struct msghdr* Expected___message;
  int Expected___flags;
  int IgnoreArg___fd;
  int IgnoreArg___message;
  int IgnoreArg___flags;

} CMOCK_sendmsg_CALL_INSTANCE;

typedef struct _CMOCK_sendmmsg_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  int ReturnVal;
  int Expected___fd;
  struct mmsghdr* Expected___vmessages;
  unsigned int Expected___vlen;
  int Expected___flags;
  int IgnoreArg___fd;
  int IgnoreArg___vmessages;
  int IgnoreArg___vlen;
  int IgnoreArg___flags;

} CMOCK_sendmmsg_CALL_INSTANCE;

typedef struct _CMOCK_recvmsg_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  ssize_t ReturnVal;
  int Expected___fd;
  struct msghdr* Expected___message;
  int Expected___flags;
  int IgnoreArg___fd;
  int IgnoreArg___message;
  int IgnoreArg___flags;

} CMOCK_recvmsg_CALL_INSTANCE;

typedef struct _CMOCK_recvmmsg_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  int ReturnVal;
  int Expected___fd;
  struct mmsghdr* Expected___vmessages;
  unsigned int Expected___vlen;
  int Expected___flags;
  struct timespec* Expected___tmo;
  int IgnoreArg___fd;
  int IgnoreArg___vmessages;
  int IgnoreArg___vlen;
  int IgnoreArg___flags;
  int IgnoreArg___tmo;

} CMOCK_recvmmsg_CALL_INSTANCE;

typedef struct _CMOCK_accept_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  int ReturnVal;
  int Expected___fd;
  __SOCKADDR_ARG Expected___addr;
  socklen_t* __restrict Expected___addr_len;
  int IgnoreArg___fd;
  int IgnoreArg___addr;
  int IgnoreArg___addr_len;

} CMOCK_accept_CALL_INSTANCE;

typedef struct _CMOCK_accept4_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  int ReturnVal;
  int Expected___fd;
  __SOCKADDR_ARG Expected___addr;
  socklen_t* __restrict Expected___addr_len;
  int Expected___flags;
  int IgnoreArg___fd;
  int IgnoreArg___addr;
  int IgnoreArg___addr_len;
  int IgnoreArg___flags;

} CMOCK_accept4_CALL_INSTANCE;

static struct MocksocketInstance
{
  int connect_IgnoreBool;
  int connect_FinalReturn;
  CMOCK_connect_CALLBACK connect_CallbackFunctionPointer;
  int connect_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE connect_CallInstance;
  int send_IgnoreBool;
  ssize_t send_FinalReturn;
  CMOCK_send_CALLBACK send_CallbackFunctionPointer;
  int send_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE send_CallInstance;
  int recv_IgnoreBool;
  ssize_t recv_FinalReturn;
  CMOCK_recv_CALLBACK recv_CallbackFunctionPointer;
  int recv_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE recv_CallInstance;
  int sendto_IgnoreBool;
  ssize_t sendto_FinalReturn;
  CMOCK_sendto_CALLBACK sendto_CallbackFunctionPointer;
  int sendto_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE sendto_CallInstance;
  int recvfrom_IgnoreBool;
  ssize_t recvfrom_FinalReturn;
  CMOCK_recvfrom_CALLBACK recvfrom_CallbackFunctionPointer;
  int recvfrom_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE recvfrom_CallInstance;
  int sendmsg_IgnoreBool;
  ssize_t sendmsg_FinalReturn;
  CMOCK_sendmsg_CALLBACK sendmsg_CallbackFunctionPointer;
  int sendmsg_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE sendmsg_CallInstance;
  int sendmmsg_IgnoreBool;
  int sendmmsg_FinalReturn;
  CMOCK_sendmmsg_CALLBACK sendmmsg_CallbackFunctionPointer;
  int sendmmsg_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE sendmmsg_CallInstance;
  int recvmsg_IgnoreBool;
  ssize_t recvmsg_FinalReturn;
  CMOCK_recvmsg_CALLBACK recvmsg_CallbackFunctionPointer;
  int recvmsg_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE recvmsg_CallInstance;
  int recvmmsg_IgnoreBool;
  int recvmmsg_FinalReturn;
  CMOCK_recvmmsg_CALLBACK recvmmsg_CallbackFunctionPointer;
  int recvmmsg_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE recvmmsg_CallInstance;
  int accept_IgnoreBool;
  int accept_FinalReturn;
  CMOCK_accept_CALLBACK accept_CallbackFunctionPointer;
  int accept_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE accept_CallInstance;
  int accept4_IgnoreBool;
  int accept4_FinalReturn;
  CMOCK_accept4_CALLBACK accept4_CallbackFunctionPointer;
  int accept4_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE accept4_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mocksocket_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.connect_IgnoreBool)
    Mock.connect_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_connect);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.connect_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.connect_CallbackFunctionPointer != NULL)
    Mock.connect_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.send_IgnoreBool)
    Mock.send_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_send);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.send_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.send_CallbackFunctionPointer != NULL)
    Mock.send_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.recv_IgnoreBool)
    Mock.recv_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_recv);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.recv_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.recv_CallbackFunctionPointer != NULL)
    Mock.recv_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.sendto_IgnoreBool)
    Mock.sendto_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_sendto);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.sendto_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.sendto_CallbackFunctionPointer != NULL)
    Mock.sendto_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.recvfrom_IgnoreBool)
    Mock.recvfrom_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_recvfrom);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.recvfrom_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.recvfrom_CallbackFunctionPointer != NULL)
    Mock.recvfrom_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.sendmsg_IgnoreBool)
    Mock.sendmsg_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_sendmsg);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.sendmsg_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.sendmsg_CallbackFunctionPointer != NULL)
    Mock.sendmsg_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.sendmmsg_IgnoreBool)
    Mock.sendmmsg_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_sendmmsg);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.sendmmsg_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.sendmmsg_CallbackFunctionPointer != NULL)
    Mock.sendmmsg_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.recvmsg_IgnoreBool)
    Mock.recvmsg_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_recvmsg);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.recvmsg_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.recvmsg_CallbackFunctionPointer != NULL)
    Mock.recvmsg_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.recvmmsg_IgnoreBool)
    Mock.recvmmsg_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_recvmmsg);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.recvmmsg_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.recvmmsg_CallbackFunctionPointer != NULL)
    Mock.recvmmsg_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.accept_IgnoreBool)
    Mock.accept_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_accept);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.accept_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.accept_CallbackFunctionPointer != NULL)
    Mock.accept_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.accept4_IgnoreBool)
    Mock.accept4_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_accept4);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.accept4_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.accept4_CallbackFunctionPointer != NULL)
    Mock.accept4_CallInstance = CMOCK_GUTS_NONE;
}

void Mocksocket_Init(void)
{
  Mocksocket_Destroy();
}

void Mocksocket_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.connect_CallbackFunctionPointer = NULL;
  Mock.connect_CallbackCalls = 0;
  Mock.send_CallbackFunctionPointer = NULL;
  Mock.send_CallbackCalls = 0;
  Mock.recv_CallbackFunctionPointer = NULL;
  Mock.recv_CallbackCalls = 0;
  Mock.sendto_CallbackFunctionPointer = NULL;
  Mock.sendto_CallbackCalls = 0;
  Mock.recvfrom_CallbackFunctionPointer = NULL;
  Mock.recvfrom_CallbackCalls = 0;
  Mock.sendmsg_CallbackFunctionPointer = NULL;
  Mock.sendmsg_CallbackCalls = 0;
  Mock.sendmmsg_CallbackFunctionPointer = NULL;
  Mock.sendmmsg_CallbackCalls = 0;
  Mock.recvmsg_CallbackFunctionPointer = NULL;
  Mock.recvmsg_CallbackCalls = 0;
  Mock.recvmmsg_CallbackFunctionPointer = NULL;
  Mock.recvmmsg_CallbackCalls = 0;
  Mock.accept_CallbackFunctionPointer = NULL;
  Mock.accept_CallbackCalls = 0;
  Mock.accept4_CallbackFunctionPointer = NULL;
  Mock.accept4_CallbackCalls = 0;
}

int connect(int __fd, __CONST_SOCKADDR_ARG __addr, socklen_t __len)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_connect_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_connect);
  cmock_call_instance = (CMOCK_connect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.connect_CallInstance);
  Mock.connect_CallInstance = CMock_Guts_MemNext(Mock.connect_CallInstance);
  if (Mock.connect_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.connect_FinalReturn;
    Mock.connect_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.connect_CallbackFunctionPointer != NULL)
  {
    return Mock.connect_CallbackFunctionPointer(__fd, __addr, __len, Mock.connect_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg___fd)
  {
    UNITY_SET_DETAILS(CMockString_connect,CMockString___fd);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected___fd, __fd, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___addr)
  {
    UNITY_SET_DETAILS(CMockString_connect,CMockString___addr);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected___addr), (void*)(&__addr), sizeof(__CONST_SOCKADDR_ARG), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___len)
  {
    UNITY_SET_DETAILS(CMockString_connect,CMockString___len);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected___len), (void*)(&__len), sizeof(socklen_t), cmock_line, CMockStringMismatch);
  }

  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_connect(CMOCK_connect_CALL_INSTANCE* cmock_call_instance, int __fd, __CONST_SOCKADDR_ARG __addr, socklen_t __len)
{
  cmock_call_instance->Expected___fd = __fd;
  cmock_call_instance->IgnoreArg___fd = 0;
  memcpy(&cmock_call_instance->Expected___addr, &__addr, sizeof(__CONST_SOCKADDR_ARG));
  cmock_call_instance->IgnoreArg___addr = 0;
  memcpy(&cmock_call_instance->Expected___len, &__len, sizeof(socklen_t));
  cmock_call_instance->IgnoreArg___len = 0;
}

void connect_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_connect_CALL_INSTANCE));
  CMOCK_connect_CALL_INSTANCE* cmock_call_instance = (CMOCK_connect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.connect_CallInstance = CMock_Guts_MemChain(Mock.connect_CallInstance, cmock_guts_index);
  Mock.connect_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.connect_IgnoreBool = (int)1;
}

void connect_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_connect_CALL_INSTANCE));
  CMOCK_connect_CALL_INSTANCE* cmock_call_instance = (CMOCK_connect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.connect_CallInstance = CMock_Guts_MemChain(Mock.connect_CallInstance, cmock_guts_index);
  Mock.connect_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void connect_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int __fd, __CONST_SOCKADDR_ARG __addr, socklen_t __len, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_connect_CALL_INSTANCE));
  CMOCK_connect_CALL_INSTANCE* cmock_call_instance = (CMOCK_connect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.connect_CallInstance = CMock_Guts_MemChain(Mock.connect_CallInstance, cmock_guts_index);
  Mock.connect_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_connect(cmock_call_instance, __fd, __addr, __len);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void connect_StubWithCallback(CMOCK_connect_CALLBACK Callback)
{
  Mock.connect_IgnoreBool = (int)0;
  Mock.connect_CallbackFunctionPointer = Callback;
}

void connect_CMockIgnoreArg___fd(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_connect_CALL_INSTANCE* cmock_call_instance = (CMOCK_connect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.connect_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___fd = 1;
}

void connect_CMockIgnoreArg___addr(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_connect_CALL_INSTANCE* cmock_call_instance = (CMOCK_connect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.connect_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___addr = 1;
}

void connect_CMockIgnoreArg___len(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_connect_CALL_INSTANCE* cmock_call_instance = (CMOCK_connect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.connect_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___len = 1;
}

ssize_t send(int __fd, const void* __buf, size_t __n, int __flags)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_send_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_send);
  cmock_call_instance = (CMOCK_send_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.send_CallInstance);
  Mock.send_CallInstance = CMock_Guts_MemNext(Mock.send_CallInstance);
  if (Mock.send_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.send_FinalReturn;
    memcpy(&Mock.send_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(ssize_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.send_CallbackFunctionPointer != NULL)
  {
    return Mock.send_CallbackFunctionPointer(__fd, __buf, __n, __flags, Mock.send_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg___fd)
  {
    UNITY_SET_DETAILS(CMockString_send,CMockString___fd);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected___fd, __fd, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___buf)
  {
    UNITY_SET_DETAILS(CMockString_send,CMockString___buf);
    if (cmock_call_instance->Expected___buf == NULL)
      { UNITY_TEST_ASSERT_NULL(__buf, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected___buf, __buf, 1, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg___n)
  {
    UNITY_SET_DETAILS(CMockString_send,CMockString___n);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected___n), (void*)(&__n), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___flags)
  {
    UNITY_SET_DETAILS(CMockString_send,CMockString___flags);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected___flags, __flags, cmock_line, CMockStringMismatch);
  }

  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_send(CMOCK_send_CALL_INSTANCE* cmock_call_instance, int __fd, const void* __buf, size_t __n, int __flags)
{
  cmock_call_instance->Expected___fd = __fd;
  cmock_call_instance->IgnoreArg___fd = 0;
  cmock_call_instance->Expected___buf = (void*)__buf;
  cmock_call_instance->IgnoreArg___buf = 0;
  memcpy(&cmock_call_instance->Expected___n, &__n, sizeof(size_t));
  cmock_call_instance->IgnoreArg___n = 0;
  cmock_call_instance->Expected___flags = __flags;
  cmock_call_instance->IgnoreArg___flags = 0;
}

void send_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, ssize_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_send_CALL_INSTANCE));
  CMOCK_send_CALL_INSTANCE* cmock_call_instance = (CMOCK_send_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.send_CallInstance = CMock_Guts_MemChain(Mock.send_CallInstance, cmock_guts_index);
  Mock.send_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.send_IgnoreBool = (int)1;
}

void send_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, ssize_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_send_CALL_INSTANCE));
  CMOCK_send_CALL_INSTANCE* cmock_call_instance = (CMOCK_send_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.send_CallInstance = CMock_Guts_MemChain(Mock.send_CallInstance, cmock_guts_index);
  Mock.send_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void send_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int __fd, const void* __buf, size_t __n, int __flags, ssize_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_send_CALL_INSTANCE));
  CMOCK_send_CALL_INSTANCE* cmock_call_instance = (CMOCK_send_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.send_CallInstance = CMock_Guts_MemChain(Mock.send_CallInstance, cmock_guts_index);
  Mock.send_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_send(cmock_call_instance, __fd, __buf, __n, __flags);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(ssize_t));
  UNITY_CLR_DETAILS();
}

void send_StubWithCallback(CMOCK_send_CALLBACK Callback)
{
  Mock.send_IgnoreBool = (int)0;
  Mock.send_CallbackFunctionPointer = Callback;
}

void send_CMockIgnoreArg___fd(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_send_CALL_INSTANCE* cmock_call_instance = (CMOCK_send_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.send_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___fd = 1;
}

void send_CMockIgnoreArg___buf(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_send_CALL_INSTANCE* cmock_call_instance = (CMOCK_send_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.send_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___buf = 1;
}

void send_CMockIgnoreArg___n(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_send_CALL_INSTANCE* cmock_call_instance = (CMOCK_send_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.send_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___n = 1;
}

void send_CMockIgnoreArg___flags(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_send_CALL_INSTANCE* cmock_call_instance = (CMOCK_send_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.send_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___flags = 1;
}

ssize_t recv(int __fd, void* __buf, size_t __n, int __flags)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_recv_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_recv);
  cmock_call_instance = (CMOCK_recv_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.recv_CallInstance);
  Mock.recv_CallInstance = CMock_Guts_MemNext(Mock.recv_CallInstance);
  if (Mock.recv_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.recv_FinalReturn;
    memcpy(&Mock.recv_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(ssize_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.recv_CallbackFunctionPointer != NULL)
  {
    return Mock.recv_CallbackFunctionPointer(__fd, __buf, __n, __flags, Mock.recv_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg___fd)
  {
    UNITY_SET_DETAILS(CMockString_recv,CMockString___fd);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected___fd, __fd, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___buf)
  {
    UNITY_SET_DETAILS(CMockString_recv,CMockString___buf);
    if (cmock_call_instance->Expected___buf == NULL)
      { UNITY_TEST_ASSERT_NULL(__buf, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected___buf, __buf, 1, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg___n)
  {
    UNITY_SET_DETAILS(CMockString_recv,CMockString___n);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected___n), (void*)(&__n), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___flags)
  {
    UNITY_SET_DETAILS(CMockString_recv,CMockString___flags);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected___flags, __flags, cmock_line, CMockStringMismatch);
  }

  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_recv(CMOCK_recv_CALL_INSTANCE* cmock_call_instance, int __fd, void* __buf, size_t __n, int __flags)
{
  cmock_call_instance->Expected___fd = __fd;
  cmock_call_instance->IgnoreArg___fd = 0;
  cmock_call_instance->Expected___buf = __buf;
  cmock_call_instance->IgnoreArg___buf = 0;
  memcpy(&cmock_call_instance->Expected___n, &__n, sizeof(size_t));
  cmock_call_instance->IgnoreArg___n = 0;
  cmock_call_instance->Expected___flags = __flags;
  cmock_call_instance->IgnoreArg___flags = 0;
}

void recv_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, ssize_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_recv_CALL_INSTANCE));
  CMOCK_recv_CALL_INSTANCE* cmock_call_instance = (CMOCK_recv_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.recv_CallInstance = CMock_Guts_MemChain(Mock.recv_CallInstance, cmock_guts_index);
  Mock.recv_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.recv_IgnoreBool = (int)1;
}

void recv_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, ssize_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_recv_CALL_INSTANCE));
  CMOCK_recv_CALL_INSTANCE* cmock_call_instance = (CMOCK_recv_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.recv_CallInstance = CMock_Guts_MemChain(Mock.recv_CallInstance, cmock_guts_index);
  Mock.recv_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void recv_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int __fd, void* __buf, size_t __n, int __flags, ssize_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_recv_CALL_INSTANCE));
  CMOCK_recv_CALL_INSTANCE* cmock_call_instance = (CMOCK_recv_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.recv_CallInstance = CMock_Guts_MemChain(Mock.recv_CallInstance, cmock_guts_index);
  Mock.recv_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_recv(cmock_call_instance, __fd, __buf, __n, __flags);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(ssize_t));
  UNITY_CLR_DETAILS();
}

void recv_StubWithCallback(CMOCK_recv_CALLBACK Callback)
{
  Mock.recv_IgnoreBool = (int)0;
  Mock.recv_CallbackFunctionPointer = Callback;
}

void recv_CMockIgnoreArg___fd(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_recv_CALL_INSTANCE* cmock_call_instance = (CMOCK_recv_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.recv_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___fd = 1;
}

void recv_CMockIgnoreArg___buf(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_recv_CALL_INSTANCE* cmock_call_instance = (CMOCK_recv_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.recv_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___buf = 1;
}

void recv_CMockIgnoreArg___n(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_recv_CALL_INSTANCE* cmock_call_instance = (CMOCK_recv_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.recv_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___n = 1;
}

void recv_CMockIgnoreArg___flags(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_recv_CALL_INSTANCE* cmock_call_instance = (CMOCK_recv_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.recv_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___flags = 1;
}

ssize_t sendto(int __fd, const void* __buf, size_t __n, int __flags, __CONST_SOCKADDR_ARG __addr, socklen_t __addr_len)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_sendto_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_sendto);
  cmock_call_instance = (CMOCK_sendto_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.sendto_CallInstance);
  Mock.sendto_CallInstance = CMock_Guts_MemNext(Mock.sendto_CallInstance);
  if (Mock.sendto_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.sendto_FinalReturn;
    memcpy(&Mock.sendto_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(ssize_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.sendto_CallbackFunctionPointer != NULL)
  {
    return Mock.sendto_CallbackFunctionPointer(__fd, __buf, __n, __flags, __addr, __addr_len, Mock.sendto_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg___fd)
  {
    UNITY_SET_DETAILS(CMockString_sendto,CMockString___fd);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected___fd, __fd, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___buf)
  {
    UNITY_SET_DETAILS(CMockString_sendto,CMockString___buf);
    if (cmock_call_instance->Expected___buf == NULL)
      { UNITY_TEST_ASSERT_NULL(__buf, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected___buf, __buf, 1, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg___n)
  {
    UNITY_SET_DETAILS(CMockString_sendto,CMockString___n);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected___n), (void*)(&__n), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___flags)
  {
    UNITY_SET_DETAILS(CMockString_sendto,CMockString___flags);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected___flags, __flags, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___addr)
  {
    UNITY_SET_DETAILS(CMockString_sendto,CMockString___addr);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected___addr), (void*)(&__addr), sizeof(__CONST_SOCKADDR_ARG), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___addr_len)
  {
    UNITY_SET_DETAILS(CMockString_sendto,CMockString___addr_len);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected___addr_len), (void*)(&__addr_len), sizeof(socklen_t), cmock_line, CMockStringMismatch);
  }

  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_sendto(CMOCK_sendto_CALL_INSTANCE* cmock_call_instance, int __fd, const void* __buf, size_t __n, int __flags, __CONST_SOCKADDR_ARG __addr, socklen_t __addr_len)
{
  cmock_call_instance->Expected___fd = __fd;
  cmock_call_instance->IgnoreArg___fd = 0;
  cmock_call_instance->Expected___buf = (void*)__buf;
  cmock_call_instance->IgnoreArg___buf = 0;
  memcpy(&cmock_call_instance->Expected___n, &__n, sizeof(size_t));
  cmock_call_instance->IgnoreArg___n = 0;
  cmock_call_instance->Expected___flags = __flags;
  cmock_call_instance->IgnoreArg___flags = 0;
  memcpy(&cmock_call_instance->Expected___addr, &__addr, sizeof(__CONST_SOCKADDR_ARG));
  cmock_call_instance->IgnoreArg___addr = 0;
  memcpy(&cmock_call_instance->Expected___addr_len, &__addr_len, sizeof(socklen_t));
  cmock_call_instance->IgnoreArg___addr_len = 0;
}

void sendto_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, ssize_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sendto_CALL_INSTANCE));
  CMOCK_sendto_CALL_INSTANCE* cmock_call_instance = (CMOCK_sendto_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sendto_CallInstance = CMock_Guts_MemChain(Mock.sendto_CallInstance, cmock_guts_index);
  Mock.sendto_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.sendto_IgnoreBool = (int)1;
}

void sendto_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, ssize_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sendto_CALL_INSTANCE));
  CMOCK_sendto_CALL_INSTANCE* cmock_call_instance = (CMOCK_sendto_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sendto_CallInstance = CMock_Guts_MemChain(Mock.sendto_CallInstance, cmock_guts_index);
  Mock.sendto_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void sendto_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int __fd, const void* __buf, size_t __n, int __flags, __CONST_SOCKADDR_ARG __addr, socklen_t __addr_len, ssize_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sendto_CALL_INSTANCE));
  CMOCK_sendto_CALL_INSTANCE* cmock_call_instance = (CMOCK_sendto_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sendto_CallInstance = CMock_Guts_MemChain(Mock.sendto_CallInstance, cmock_guts_index);
  Mock.sendto_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_sendto(cmock_call_instance, __fd, __buf, __n, __flags, __addr, __addr_len);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(ssize_t));
  UNITY_CLR_DETAILS();
}

void sendto_StubWithCallback(CMOCK_sendto_CALLBACK Callback)
{
  Mock.sendto_IgnoreBool = (int)0;
  Mock.sendto_CallbackFunctionPointer = Callback;
}

void sendto_CMockIgnoreArg___fd(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_sendto_CALL_INSTANCE* cmock_call_instance = (CMOCK_sendto_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.sendto_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___fd = 1;
}

void sendto_CMockIgnoreArg___buf(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_sendto_CALL_INSTANCE* cmock_call_instance = (CMOCK_sendto_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.sendto_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___buf = 1;
}

void sendto_CMockIgnoreArg___n(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_sendto_CALL_INSTANCE* cmock_call_instance = (CMOCK_sendto_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.sendto_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___n = 1;
}

void sendto_CMockIgnoreArg___flags(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_sendto_CALL_INSTANCE* cmock_call_instance = (CMOCK_sendto_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.sendto_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___flags = 1;
}

void sendto_CMockIgnoreArg___addr(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_sendto_CALL_INSTANCE* cmock_call_instance = (CMOCK_sendto_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.sendto_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___addr = 1;
}

void sendto_CMockIgnoreArg___addr_len(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_sendto_CALL_INSTANCE* cmock_call_instance = (CMOCK_sendto_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.sendto_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___addr_len = 1;
}

ssize_t recvfrom(int __fd, void* __restrict __buf, size_t __n, int __flags, __SOCKADDR_ARG __addr, socklen_t* __restrict __addr_len)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_recvfrom_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_recvfrom);
  cmock_call_instance = (CMOCK_recvfrom_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.recvfrom_CallInstance);
  Mock.recvfrom_CallInstance = CMock_Guts_MemNext(Mock.recvfrom_CallInstance);
  if (Mock.recvfrom_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.recvfrom_FinalReturn;
    memcpy(&Mock.recvfrom_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(ssize_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.recvfrom_CallbackFunctionPointer != NULL)
  {
    return Mock.recvfrom_CallbackFunctionPointer(__fd, __buf, __n, __flags, __addr, __addr_len, Mock.recvfrom_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg___fd)
  {
    UNITY_SET_DETAILS(CMockString_recvfrom,CMockString___fd);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected___fd, __fd, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___buf)
  {
    UNITY_SET_DETAILS(CMockString_recvfrom,CMockString___buf);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected___buf), (void*)(&__buf), sizeof(void* __restrict), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___n)
  {
    UNITY_SET_DETAILS(CMockString_recvfrom,CMockString___n);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected___n), (void*)(&__n), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___flags)
  {
    UNITY_SET_DETAILS(CMockString_recvfrom,CMockString___flags);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected___flags, __flags, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___addr)
  {
    UNITY_SET_DETAILS(CMockString_recvfrom,CMockString___addr);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected___addr), (void*)(&__addr), sizeof(__SOCKADDR_ARG), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___addr_len)
  {
    UNITY_SET_DETAILS(CMockString_recvfrom,CMockString___addr_len);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected___addr_len), (void*)(&__addr_len), sizeof(socklen_t* __restrict), cmock_line, CMockStringMismatch);
  }

  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_recvfrom(CMOCK_recvfrom_CALL_INSTANCE* cmock_call_instance, int __fd, void* __restrict __buf, size_t __n, int __flags, __SOCKADDR_ARG __addr, socklen_t* __restrict __addr_len)
{
  cmock_call_instance->Expected___fd = __fd;
  cmock_call_instance->IgnoreArg___fd = 0;
  cmock_call_instance->Expected___buf = __buf;
  cmock_call_instance->IgnoreArg___buf = 0;
  memcpy(&cmock_call_instance->Expected___n, &__n, sizeof(size_t));
  cmock_call_instance->IgnoreArg___n = 0;
  cmock_call_instance->Expected___flags = __flags;
  cmock_call_instance->IgnoreArg___flags = 0;
  memcpy(&cmock_call_instance->Expected___addr, &__addr, sizeof(__SOCKADDR_ARG));
  cmock_call_instance->IgnoreArg___addr = 0;
  cmock_call_instance->Expected___addr_len = __addr_len;
  cmock_call_instance->IgnoreArg___addr_len = 0;
}

void recvfrom_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, ssize_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_recvfrom_CALL_INSTANCE));
  CMOCK_recvfrom_CALL_INSTANCE* cmock_call_instance = (CMOCK_recvfrom_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.recvfrom_CallInstance = CMock_Guts_MemChain(Mock.recvfrom_CallInstance, cmock_guts_index);
  Mock.recvfrom_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.recvfrom_IgnoreBool = (int)1;
}

void recvfrom_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, ssize_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_recvfrom_CALL_INSTANCE));
  CMOCK_recvfrom_CALL_INSTANCE* cmock_call_instance = (CMOCK_recvfrom_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.recvfrom_CallInstance = CMock_Guts_MemChain(Mock.recvfrom_CallInstance, cmock_guts_index);
  Mock.recvfrom_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void recvfrom_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int __fd, void* __restrict __buf, size_t __n, int __flags, __SOCKADDR_ARG __addr, socklen_t* __restrict __addr_len, ssize_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_recvfrom_CALL_INSTANCE));
  CMOCK_recvfrom_CALL_INSTANCE* cmock_call_instance = (CMOCK_recvfrom_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.recvfrom_CallInstance = CMock_Guts_MemChain(Mock.recvfrom_CallInstance, cmock_guts_index);
  Mock.recvfrom_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_recvfrom(cmock_call_instance, __fd, __buf, __n, __flags, __addr, __addr_len);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(ssize_t));
  UNITY_CLR_DETAILS();
}

void recvfrom_StubWithCallback(CMOCK_recvfrom_CALLBACK Callback)
{
  Mock.recvfrom_IgnoreBool = (int)0;
  Mock.recvfrom_CallbackFunctionPointer = Callback;
}

void recvfrom_CMockIgnoreArg___fd(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_recvfrom_CALL_INSTANCE* cmock_call_instance = (CMOCK_recvfrom_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.recvfrom_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___fd = 1;
}

void recvfrom_CMockIgnoreArg___buf(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_recvfrom_CALL_INSTANCE* cmock_call_instance = (CMOCK_recvfrom_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.recvfrom_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___buf = 1;
}

void recvfrom_CMockIgnoreArg___n(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_recvfrom_CALL_INSTANCE* cmock_call_instance = (CMOCK_recvfrom_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.recvfrom_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___n = 1;
}

void recvfrom_CMockIgnoreArg___flags(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_recvfrom_CALL_INSTANCE* cmock_call_instance = (CMOCK_recvfrom_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.recvfrom_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___flags = 1;
}

void recvfrom_CMockIgnoreArg___addr(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_recvfrom_CALL_INSTANCE* cmock_call_instance = (CMOCK_recvfrom_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.recvfrom_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___addr = 1;
}

void recvfrom_CMockIgnoreArg___addr_len(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_recvfrom_CALL_INSTANCE* cmock_call_instance = (CMOCK_recvfrom_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.recvfrom_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___addr_len = 1;
}

ssize_t sendmsg(int __fd, const struct msghdr* __message, int __flags)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_sendmsg_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_sendmsg);
  cmock_call_instance = (CMOCK_sendmsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.sendmsg_CallInstance);
  Mock.sendmsg_CallInstance = CMock_Guts_MemNext(Mock.sendmsg_CallInstance);
  if (Mock.sendmsg_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.sendmsg_FinalReturn;
    memcpy(&Mock.sendmsg_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(ssize_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.sendmsg_CallbackFunctionPointer != NULL)
  {
    return Mock.sendmsg_CallbackFunctionPointer(__fd, __message, __flags, Mock.sendmsg_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg___fd)
  {
    UNITY_SET_DETAILS(CMockString_sendmsg,CMockString___fd);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected___fd, __fd, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___message)
  {
    UNITY_SET_DETAILS(CMockString_sendmsg,CMockString___message);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected___message), (void*)(__message), sizeof(struct msghdr), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___flags)
  {
    UNITY_SET_DETAILS(CMockString_sendmsg,CMockString___flags);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected___flags, __flags, cmock_line, CMockStringMismatch);
  }

  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_sendmsg(CMOCK_sendmsg_CALL_INSTANCE* cmock_call_instance, int __fd, const struct msghdr* __message, int __flags)
{
  cmock_call_instance->Expected___fd = __fd;
  cmock_call_instance->IgnoreArg___fd = 0;
  cmock_call_instance->Expected___message = (struct msghdr*)__message;
  cmock_call_instance->IgnoreArg___message = 0;
  cmock_call_instance->Expected___flags = __flags;
  cmock_call_instance->IgnoreArg___flags = 0;
}

void sendmsg_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, ssize_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sendmsg_CALL_INSTANCE));
  CMOCK_sendmsg_CALL_INSTANCE* cmock_call_instance = (CMOCK_sendmsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sendmsg_CallInstance = CMock_Guts_MemChain(Mock.sendmsg_CallInstance, cmock_guts_index);
  Mock.sendmsg_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.sendmsg_IgnoreBool = (int)1;
}

void sendmsg_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, ssize_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sendmsg_CALL_INSTANCE));
  CMOCK_sendmsg_CALL_INSTANCE* cmock_call_instance = (CMOCK_sendmsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sendmsg_CallInstance = CMock_Guts_MemChain(Mock.sendmsg_CallInstance, cmock_guts_index);
  Mock.sendmsg_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void sendmsg_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int __fd, const struct msghdr* __message, int __flags, ssize_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sendmsg_CALL_INSTANCE));
  CMOCK_sendmsg_CALL_INSTANCE* cmock_call_instance = (CMOCK_sendmsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sendmsg_CallInstance = CMock_Guts_MemChain(Mock.sendmsg_CallInstance, cmock_guts_index);
  Mock.sendmsg_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_sendmsg(cmock_call_instance, __fd, __message, __flags);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(ssize_t));
  UNITY_CLR_DETAILS();
}

void sendmsg_StubWithCallback(CMOCK_sendmsg_CALLBACK Callback)
{
  Mock.sendmsg_IgnoreBool = (int)0;
  Mock.sendmsg_CallbackFunctionPointer = Callback;
}

void sendmsg_CMockIgnoreArg___fd(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_sendmsg_CALL_INSTANCE* cmock_call_instance = (CMOCK_sendmsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.sendmsg_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___fd = 1;
}

void sendmsg_CMockIgnoreArg___message(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_sendmsg_CALL_INSTANCE* cmock_call_instance = (CMOCK_sendmsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.sendmsg_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___message = 1;
}

void sendmsg_CMockIgnoreArg___flags(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_sendmsg_CALL_INSTANCE* cmock_call_instance = (CMOCK_sendmsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.sendmsg_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___flags = 1;
}

int sendmmsg(int __fd, struct mmsghdr* __vmessages, unsigned int __vlen, int __flags)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_sendmmsg_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_sendmmsg);
  cmock_call_instance = (CMOCK_sendmmsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.sendmmsg_CallInstance);
  Mock.sendmmsg_CallInstance = CMock_Guts_MemNext(Mock.sendmmsg_CallInstance);
  if (Mock.sendmmsg_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.sendmmsg_FinalReturn;
    Mock.sendmmsg_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.sendmmsg_CallbackFunctionPointer != NULL)
  {
    return Mock.sendmmsg_CallbackFunctionPointer(__fd, __vmessages, __vlen, __flags, Mock.sendmmsg_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg___fd)
  {
    UNITY_SET_DETAILS(CMockString_sendmmsg,CMockString___fd);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected___fd, __fd, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___vmessages)
  {
    UNITY_SET_DETAILS(CMockString_sendmmsg,CMockString___vmessages);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected___vmessages), (void*)(__vmessages), sizeof(struct mmsghdr), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___vlen)
  {
    UNITY_SET_DETAILS(CMockString_sendmmsg,CMockString___vlen);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected___vlen, __vlen, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___flags)
  {
    UNITY_SET_DETAILS(CMockString_sendmmsg,CMockString___flags);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected___flags, __flags, cmock_line, CMockStringMismatch);
  }

  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_sendmmsg(CMOCK_sendmmsg_CALL_INSTANCE* cmock_call_instance, int __fd, struct mmsghdr* __vmessages, unsigned int __vlen, int __flags)
{
  cmock_call_instance->Expected___fd = __fd;
  cmock_call_instance->IgnoreArg___fd = 0;
  cmock_call_instance->Expected___vmessages = __vmessages;
  cmock_call_instance->IgnoreArg___vmessages = 0;
  cmock_call_instance->Expected___vlen = __vlen;
  cmock_call_instance->IgnoreArg___vlen = 0;
  cmock_call_instance->Expected___flags = __flags;
  cmock_call_instance->IgnoreArg___flags = 0;
}

void sendmmsg_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sendmmsg_CALL_INSTANCE));
  CMOCK_sendmmsg_CALL_INSTANCE* cmock_call_instance = (CMOCK_sendmmsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sendmmsg_CallInstance = CMock_Guts_MemChain(Mock.sendmmsg_CallInstance, cmock_guts_index);
  Mock.sendmmsg_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.sendmmsg_IgnoreBool = (int)1;
}

void sendmmsg_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sendmmsg_CALL_INSTANCE));
  CMOCK_sendmmsg_CALL_INSTANCE* cmock_call_instance = (CMOCK_sendmmsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sendmmsg_CallInstance = CMock_Guts_MemChain(Mock.sendmmsg_CallInstance, cmock_guts_index);
  Mock.sendmmsg_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void sendmmsg_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int __fd, struct mmsghdr* __vmessages, unsigned int __vlen, int __flags, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sendmmsg_CALL_INSTANCE));
  CMOCK_sendmmsg_CALL_INSTANCE* cmock_call_instance = (CMOCK_sendmmsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sendmmsg_CallInstance = CMock_Guts_MemChain(Mock.sendmmsg_CallInstance, cmock_guts_index);
  Mock.sendmmsg_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_sendmmsg(cmock_call_instance, __fd, __vmessages, __vlen, __flags);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void sendmmsg_StubWithCallback(CMOCK_sendmmsg_CALLBACK Callback)
{
  Mock.sendmmsg_IgnoreBool = (int)0;
  Mock.sendmmsg_CallbackFunctionPointer = Callback;
}

void sendmmsg_CMockIgnoreArg___fd(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_sendmmsg_CALL_INSTANCE* cmock_call_instance = (CMOCK_sendmmsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.sendmmsg_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___fd = 1;
}

void sendmmsg_CMockIgnoreArg___vmessages(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_sendmmsg_CALL_INSTANCE* cmock_call_instance = (CMOCK_sendmmsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.sendmmsg_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___vmessages = 1;
}

void sendmmsg_CMockIgnoreArg___vlen(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_sendmmsg_CALL_INSTANCE* cmock_call_instance = (CMOCK_sendmmsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.sendmmsg_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___vlen = 1;
}

void sendmmsg_CMockIgnoreArg___flags(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_sendmmsg_CALL_INSTANCE* cmock_call_instance = (CMOCK_sendmmsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.sendmmsg_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___flags = 1;
}

ssize_t recvmsg(int __fd, struct msghdr* __message, int __flags)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_recvmsg_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_recvmsg);
  cmock_call_instance = (CMOCK_recvmsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.recvmsg_CallInstance);
  Mock.recvmsg_CallInstance = CMock_Guts_MemNext(Mock.recvmsg_CallInstance);
  if (Mock.recvmsg_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.recvmsg_FinalReturn;
    memcpy(&Mock.recvmsg_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(ssize_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.recvmsg_CallbackFunctionPointer != NULL)
  {
    return Mock.recvmsg_CallbackFunctionPointer(__fd, __message, __flags, Mock.recvmsg_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg___fd)
  {
    UNITY_SET_DETAILS(CMockString_recvmsg,CMockString___fd);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected___fd, __fd, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___message)
  {
    UNITY_SET_DETAILS(CMockString_recvmsg,CMockString___message);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected___message), (void*)(__message), sizeof(struct msghdr), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___flags)
  {
    UNITY_SET_DETAILS(CMockString_recvmsg,CMockString___flags);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected___flags, __flags, cmock_line, CMockStringMismatch);
  }

  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_recvmsg(CMOCK_recvmsg_CALL_INSTANCE* cmock_call_instance, int __fd, struct msghdr* __message, int __flags)
{
  cmock_call_instance->Expected___fd = __fd;
  cmock_call_instance->IgnoreArg___fd = 0;
  cmock_call_instance->Expected___message = __message;
  cmock_call_instance->IgnoreArg___message = 0;
  cmock_call_instance->Expected___flags = __flags;
  cmock_call_instance->IgnoreArg___flags = 0;
}

void recvmsg_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, ssize_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_recvmsg_CALL_INSTANCE));
  CMOCK_recvmsg_CALL_INSTANCE* cmock_call_instance = (CMOCK_recvmsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.recvmsg_CallInstance = CMock_Guts_MemChain(Mock.recvmsg_CallInstance, cmock_guts_index);
  Mock.recvmsg_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.recvmsg_IgnoreBool = (int)1;
}

void recvmsg_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, ssize_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_recvmsg_CALL_INSTANCE));
  CMOCK_recvmsg_CALL_INSTANCE* cmock_call_instance = (CMOCK_recvmsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.recvmsg_CallInstance = CMock_Guts_MemChain(Mock.recvmsg_CallInstance, cmock_guts_index);
  Mock.recvmsg_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void recvmsg_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int __fd, struct msghdr* __message, int __flags, ssize_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_recvmsg_CALL_INSTANCE));
  CMOCK_recvmsg_CALL_INSTANCE* cmock_call_instance = (CMOCK_recvmsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.recvmsg_CallInstance = CMock_Guts_MemChain(Mock.recvmsg_CallInstance, cmock_guts_index);
  Mock.recvmsg_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_recvmsg(cmock_call_instance, __fd, __message, __flags);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(ssize_t));
  UNITY_CLR_DETAILS();
}

void recvmsg_StubWithCallback(CMOCK_recvmsg_CALLBACK Callback)
{
  Mock.recvmsg_IgnoreBool = (int)0;
  Mock.recvmsg_CallbackFunctionPointer = Callback;
}

void recvmsg_CMockIgnoreArg___fd(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_recvmsg_CALL_INSTANCE* cmock_call_instance = (CMOCK_recvmsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.recvmsg_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___fd = 1;
}

void recvmsg_CMockIgnoreArg___message(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_recvmsg_CALL_INSTANCE* cmock_call_instance = (CMOCK_recvmsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.recvmsg_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___message = 1;
}

void recvmsg_CMockIgnoreArg___flags(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_recvmsg_CALL_INSTANCE* cmock_call_instance = (CMOCK_recvmsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.recvmsg_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___flags = 1;
}
#if __GNUC__ >= 5
int recvmmsg(int __fd, struct mmsghdr* __vmessages, unsigned int __vlen, int __flags, struct timespec* __tmo)
#else
int recvmmsg(int __fd, struct mmsghdr* __vmessages, unsigned int __vlen, int __flags, __const struct timespec* __tmo)
#endif
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_recvmmsg_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_recvmmsg);
  cmock_call_instance = (CMOCK_recvmmsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.recvmmsg_CallInstance);
  Mock.recvmmsg_CallInstance = CMock_Guts_MemNext(Mock.recvmmsg_CallInstance);
  if (Mock.recvmmsg_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.recvmmsg_FinalReturn;
    Mock.recvmmsg_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  // if (Mock.recvmmsg_CallbackFunctionPointer != NULL)
  // {
  //   return Mock.recvmmsg_CallbackFunctionPointer(__fd, __vmessages, __vlen, __flags, __tmo, Mock.recvmmsg_CallbackCalls++);
  // }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg___fd)
  {
    UNITY_SET_DETAILS(CMockString_recvmmsg,CMockString___fd);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected___fd, __fd, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___vmessages)
  {
    UNITY_SET_DETAILS(CMockString_recvmmsg,CMockString___vmessages);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected___vmessages), (void*)(__vmessages), sizeof(struct mmsghdr), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___vlen)
  {
    UNITY_SET_DETAILS(CMockString_recvmmsg,CMockString___vlen);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected___vlen, __vlen, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___flags)
  {
    UNITY_SET_DETAILS(CMockString_recvmmsg,CMockString___flags);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected___flags, __flags, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___tmo)
  {
    UNITY_SET_DETAILS(CMockString_recvmmsg,CMockString___tmo);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected___tmo), (void*)(__tmo), sizeof(struct timespec), cmock_line, CMockStringMismatch);
  }

  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_recvmmsg(CMOCK_recvmmsg_CALL_INSTANCE* cmock_call_instance, int __fd, struct mmsghdr* __vmessages, unsigned int __vlen, int __flags, struct timespec* __tmo)
{
  cmock_call_instance->Expected___fd = __fd;
  cmock_call_instance->IgnoreArg___fd = 0;
  cmock_call_instance->Expected___vmessages = __vmessages;
  cmock_call_instance->IgnoreArg___vmessages = 0;
  cmock_call_instance->Expected___vlen = __vlen;
  cmock_call_instance->IgnoreArg___vlen = 0;
  cmock_call_instance->Expected___flags = __flags;
  cmock_call_instance->IgnoreArg___flags = 0;
  cmock_call_instance->Expected___tmo = __tmo;
  cmock_call_instance->IgnoreArg___tmo = 0;
}

void recvmmsg_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_recvmmsg_CALL_INSTANCE));
  CMOCK_recvmmsg_CALL_INSTANCE* cmock_call_instance = (CMOCK_recvmmsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.recvmmsg_CallInstance = CMock_Guts_MemChain(Mock.recvmmsg_CallInstance, cmock_guts_index);
  Mock.recvmmsg_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.recvmmsg_IgnoreBool = (int)1;
}

void recvmmsg_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_recvmmsg_CALL_INSTANCE));
  CMOCK_recvmmsg_CALL_INSTANCE* cmock_call_instance = (CMOCK_recvmmsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.recvmmsg_CallInstance = CMock_Guts_MemChain(Mock.recvmmsg_CallInstance, cmock_guts_index);
  Mock.recvmmsg_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void recvmmsg_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int __fd, struct mmsghdr* __vmessages, unsigned int __vlen, int __flags, struct timespec* __tmo, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_recvmmsg_CALL_INSTANCE));
  CMOCK_recvmmsg_CALL_INSTANCE* cmock_call_instance = (CMOCK_recvmmsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.recvmmsg_CallInstance = CMock_Guts_MemChain(Mock.recvmmsg_CallInstance, cmock_guts_index);
  Mock.recvmmsg_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_recvmmsg(cmock_call_instance, __fd, __vmessages, __vlen, __flags, __tmo);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void recvmmsg_StubWithCallback(CMOCK_recvmmsg_CALLBACK Callback)
{
  Mock.recvmmsg_IgnoreBool = (int)0;
  Mock.recvmmsg_CallbackFunctionPointer = Callback;
}

void recvmmsg_CMockIgnoreArg___fd(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_recvmmsg_CALL_INSTANCE* cmock_call_instance = (CMOCK_recvmmsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.recvmmsg_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___fd = 1;
}

void recvmmsg_CMockIgnoreArg___vmessages(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_recvmmsg_CALL_INSTANCE* cmock_call_instance = (CMOCK_recvmmsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.recvmmsg_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___vmessages = 1;
}

void recvmmsg_CMockIgnoreArg___vlen(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_recvmmsg_CALL_INSTANCE* cmock_call_instance = (CMOCK_recvmmsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.recvmmsg_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___vlen = 1;
}

void recvmmsg_CMockIgnoreArg___flags(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_recvmmsg_CALL_INSTANCE* cmock_call_instance = (CMOCK_recvmmsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.recvmmsg_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___flags = 1;
}

void recvmmsg_CMockIgnoreArg___tmo(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_recvmmsg_CALL_INSTANCE* cmock_call_instance = (CMOCK_recvmmsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.recvmmsg_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___tmo = 1;
}

int accept(int __fd, __SOCKADDR_ARG __addr, socklen_t* __restrict __addr_len)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_accept_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_accept);
  cmock_call_instance = (CMOCK_accept_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.accept_CallInstance);
  Mock.accept_CallInstance = CMock_Guts_MemNext(Mock.accept_CallInstance);
  if (Mock.accept_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.accept_FinalReturn;
    Mock.accept_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.accept_CallbackFunctionPointer != NULL)
  {
    return Mock.accept_CallbackFunctionPointer(__fd, __addr, __addr_len, Mock.accept_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg___fd)
  {
    UNITY_SET_DETAILS(CMockString_accept,CMockString___fd);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected___fd, __fd, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___addr)
  {
    UNITY_SET_DETAILS(CMockString_accept,CMockString___addr);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected___addr), (void*)(&__addr), sizeof(__SOCKADDR_ARG), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___addr_len)
  {
    UNITY_SET_DETAILS(CMockString_accept,CMockString___addr_len);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected___addr_len), (void*)(&__addr_len), sizeof(socklen_t* __restrict), cmock_line, CMockStringMismatch);
  }

  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_accept(CMOCK_accept_CALL_INSTANCE* cmock_call_instance, int __fd, __SOCKADDR_ARG __addr, socklen_t* __restrict __addr_len)
{
  cmock_call_instance->Expected___fd = __fd;
  cmock_call_instance->IgnoreArg___fd = 0;
  memcpy(&cmock_call_instance->Expected___addr, &__addr, sizeof(__SOCKADDR_ARG));
  cmock_call_instance->IgnoreArg___addr = 0;
  cmock_call_instance->Expected___addr_len = __addr_len;
  cmock_call_instance->IgnoreArg___addr_len = 0;
}

void accept_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_accept_CALL_INSTANCE));
  CMOCK_accept_CALL_INSTANCE* cmock_call_instance = (CMOCK_accept_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.accept_CallInstance = CMock_Guts_MemChain(Mock.accept_CallInstance, cmock_guts_index);
  Mock.accept_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.accept_IgnoreBool = (int)1;
}

void accept_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_accept_CALL_INSTANCE));
  CMOCK_accept_CALL_INSTANCE* cmock_call_instance = (CMOCK_accept_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.accept_CallInstance = CMock_Guts_MemChain(Mock.accept_CallInstance, cmock_guts_index);
  Mock.accept_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void accept_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int __fd, __SOCKADDR_ARG __addr, socklen_t* __restrict __addr_len, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_accept_CALL_INSTANCE));
  CMOCK_accept_CALL_INSTANCE* cmock_call_instance = (CMOCK_accept_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.accept_CallInstance = CMock_Guts_MemChain(Mock.accept_CallInstance, cmock_guts_index);
  Mock.accept_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_accept(cmock_call_instance, __fd, __addr, __addr_len);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void accept_StubWithCallback(CMOCK_accept_CALLBACK Callback)
{
  Mock.accept_IgnoreBool = (int)0;
  Mock.accept_CallbackFunctionPointer = Callback;
}

void accept_CMockIgnoreArg___fd(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_accept_CALL_INSTANCE* cmock_call_instance = (CMOCK_accept_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.accept_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___fd = 1;
}

void accept_CMockIgnoreArg___addr(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_accept_CALL_INSTANCE* cmock_call_instance = (CMOCK_accept_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.accept_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___addr = 1;
}

void accept_CMockIgnoreArg___addr_len(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_accept_CALL_INSTANCE* cmock_call_instance = (CMOCK_accept_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.accept_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___addr_len = 1;
}

int accept4(int __fd, __SOCKADDR_ARG __addr, socklen_t* __restrict __addr_len, int __flags)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_accept4_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_accept4);
  cmock_call_instance = (CMOCK_accept4_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.accept4_CallInstance);
  Mock.accept4_CallInstance = CMock_Guts_MemNext(Mock.accept4_CallInstance);
  if (Mock.accept4_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.accept4_FinalReturn;
    Mock.accept4_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.accept4_CallbackFunctionPointer != NULL)
  {
    return Mock.accept4_CallbackFunctionPointer(__fd, __addr, __addr_len, __flags, Mock.accept4_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg___fd)
  {
    UNITY_SET_DETAILS(CMockString_accept4,CMockString___fd);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected___fd, __fd, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___addr)
  {
    UNITY_SET_DETAILS(CMockString_accept4,CMockString___addr);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected___addr), (void*)(&__addr), sizeof(__SOCKADDR_ARG), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___addr_len)
  {
    UNITY_SET_DETAILS(CMockString_accept4,CMockString___addr_len);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected___addr_len), (void*)(&__addr_len), sizeof(socklen_t* __restrict), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg___flags)
  {
    UNITY_SET_DETAILS(CMockString_accept4,CMockString___flags);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected___flags, __flags, cmock_line, CMockStringMismatch);
  }

  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_accept4(CMOCK_accept4_CALL_INSTANCE* cmock_call_instance, int __fd, __SOCKADDR_ARG __addr, socklen_t* __restrict __addr_len, int __flags)
{
  cmock_call_instance->Expected___fd = __fd;
  cmock_call_instance->IgnoreArg___fd = 0;
  memcpy(&cmock_call_instance->Expected___addr, &__addr, sizeof(__SOCKADDR_ARG));
  cmock_call_instance->IgnoreArg___addr = 0;
  cmock_call_instance->Expected___addr_len = __addr_len;
  cmock_call_instance->IgnoreArg___addr_len = 0;
  cmock_call_instance->Expected___flags = __flags;
  cmock_call_instance->IgnoreArg___flags = 0;
}

void accept4_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_accept4_CALL_INSTANCE));
  CMOCK_accept4_CALL_INSTANCE* cmock_call_instance = (CMOCK_accept4_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.accept4_CallInstance = CMock_Guts_MemChain(Mock.accept4_CallInstance, cmock_guts_index);
  Mock.accept4_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.accept4_IgnoreBool = (int)1;
}

void accept4_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_accept4_CALL_INSTANCE));
  CMOCK_accept4_CALL_INSTANCE* cmock_call_instance = (CMOCK_accept4_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.accept4_CallInstance = CMock_Guts_MemChain(Mock.accept4_CallInstance, cmock_guts_index);
  Mock.accept4_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void accept4_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int __fd, __SOCKADDR_ARG __addr, socklen_t* __restrict __addr_len, int __flags, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_accept4_CALL_INSTANCE));
  CMOCK_accept4_CALL_INSTANCE* cmock_call_instance = (CMOCK_accept4_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.accept4_CallInstance = CMock_Guts_MemChain(Mock.accept4_CallInstance, cmock_guts_index);
  Mock.accept4_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_accept4(cmock_call_instance, __fd, __addr, __addr_len, __flags);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void accept4_StubWithCallback(CMOCK_accept4_CALLBACK Callback)
{
  Mock.accept4_IgnoreBool = (int)0;
  Mock.accept4_CallbackFunctionPointer = Callback;
}

void accept4_CMockIgnoreArg___fd(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_accept4_CALL_INSTANCE* cmock_call_instance = (CMOCK_accept4_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.accept4_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___fd = 1;
}

void accept4_CMockIgnoreArg___addr(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_accept4_CALL_INSTANCE* cmock_call_instance = (CMOCK_accept4_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.accept4_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___addr = 1;
}

void accept4_CMockIgnoreArg___addr_len(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_accept4_CALL_INSTANCE* cmock_call_instance = (CMOCK_accept4_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.accept4_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___addr_len = 1;
}

void accept4_CMockIgnoreArg___flags(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_accept4_CALL_INSTANCE* cmock_call_instance = (CMOCK_accept4_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.accept4_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg___flags = 1;
}

