/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockrt_transport.h"

static const char *CMockString_endpoint = "endpoint";
static const char *CMockString_len = "len";
static const char *CMockString_msg_initialize_transport = "msg_initialize_transport";
static const char *CMockString_msg_send_multicast_packet = "msg_send_multicast_packet";
static const char *CMockString_msg_send_unicast_packet = "msg_send_unicast_packet";
static const char *CMockString_msg_set_receive_handler = "msg_set_receive_handler";
static const char *CMockString_msg_terminate_transport = "msg_terminate_transport";
static const char *CMockString_msg_unset_receive_handler = "msg_unset_receive_handler";
static const char *CMockString_packet = "packet";
static const char *CMockString_recv_handler = "recv_handler";

typedef struct _CMOCK_msg_initialize_transport_CALL_INSTANCE {
	UNITY_LINE_TYPE LineNumber;
	CMOCK_ARG_MODE IgnoreMode;
	int ReturnVal;

} CMOCK_msg_initialize_transport_CALL_INSTANCE;

typedef struct _CMOCK_msg_terminate_transport_CALL_INSTANCE {
	UNITY_LINE_TYPE LineNumber;
	CMOCK_ARG_MODE IgnoreMode;

} CMOCK_msg_terminate_transport_CALL_INSTANCE;

typedef struct _CMOCK_msg_send_unicast_packet_CALL_INSTANCE {
	UNITY_LINE_TYPE LineNumber;
	CMOCK_ARG_MODE IgnoreMode;
	uint8_t *Expected_packet;
	uint16_t Expected_len;
	ocf_endpoint_s *Expected_endpoint;
	int IgnoreArg_packet;
	int IgnoreArg_len;
	int IgnoreArg_endpoint;

} CMOCK_msg_send_unicast_packet_CALL_INSTANCE;

typedef struct _CMOCK_msg_send_multicast_packet_CALL_INSTANCE {
	UNITY_LINE_TYPE LineNumber;
	CMOCK_ARG_MODE IgnoreMode;
	uint8_t *Expected_packet;
	uint16_t Expected_len;
	int IgnoreArg_packet;
	int IgnoreArg_len;

} CMOCK_msg_send_multicast_packet_CALL_INSTANCE;

typedef struct _CMOCK_msg_set_receive_handler_CALL_INSTANCE {
	UNITY_LINE_TYPE LineNumber;
	CMOCK_ARG_MODE IgnoreMode;
	int ReturnVal;
	msg_receive_handler Expected_recv_handler;
	int IgnoreArg_recv_handler;

} CMOCK_msg_set_receive_handler_CALL_INSTANCE;

typedef struct _CMOCK_msg_unset_receive_handler_CALL_INSTANCE {
	UNITY_LINE_TYPE LineNumber;
	CMOCK_ARG_MODE IgnoreMode;
	int ReturnVal;

} CMOCK_msg_unset_receive_handler_CALL_INSTANCE;

static struct Mockrt_transportInstance {
	int msg_initialize_transport_IgnoreBool;
	int msg_initialize_transport_FinalReturn;
	CMOCK_msg_initialize_transport_CALLBACK msg_initialize_transport_CallbackFunctionPointer;
	int msg_initialize_transport_CallbackCalls;
	CMOCK_MEM_INDEX_TYPE msg_initialize_transport_CallInstance;
	int msg_terminate_transport_IgnoreBool;
	CMOCK_msg_terminate_transport_CALLBACK msg_terminate_transport_CallbackFunctionPointer;
	int msg_terminate_transport_CallbackCalls;
	CMOCK_MEM_INDEX_TYPE msg_terminate_transport_CallInstance;
	int msg_send_unicast_packet_IgnoreBool;
	CMOCK_msg_send_unicast_packet_CALLBACK msg_send_unicast_packet_CallbackFunctionPointer;
	int msg_send_unicast_packet_CallbackCalls;
	CMOCK_MEM_INDEX_TYPE msg_send_unicast_packet_CallInstance;
	int msg_send_multicast_packet_IgnoreBool;
	CMOCK_msg_send_multicast_packet_CALLBACK msg_send_multicast_packet_CallbackFunctionPointer;
	int msg_send_multicast_packet_CallbackCalls;
	CMOCK_MEM_INDEX_TYPE msg_send_multicast_packet_CallInstance;
	int msg_set_receive_handler_IgnoreBool;
	int msg_set_receive_handler_FinalReturn;
	CMOCK_msg_set_receive_handler_CALLBACK msg_set_receive_handler_CallbackFunctionPointer;
	int msg_set_receive_handler_CallbackCalls;
	CMOCK_MEM_INDEX_TYPE msg_set_receive_handler_CallInstance;
	int msg_unset_receive_handler_IgnoreBool;
	int msg_unset_receive_handler_FinalReturn;
	CMOCK_msg_unset_receive_handler_CALLBACK msg_unset_receive_handler_CallbackFunctionPointer;
	int msg_unset_receive_handler_CallbackCalls;
	CMOCK_MEM_INDEX_TYPE msg_unset_receive_handler_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockrt_transport_Verify(void)
{
	UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
	if (Mock.msg_initialize_transport_IgnoreBool) {
		Mock.msg_initialize_transport_CallInstance = CMOCK_GUTS_NONE;
	}
	UNITY_SET_DETAIL(CMockString_msg_initialize_transport);
	UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.msg_initialize_transport_CallInstance, cmock_line, CMockStringCalledLess);
	if (Mock.msg_initialize_transport_CallbackFunctionPointer != NULL) {
		Mock.msg_initialize_transport_CallInstance = CMOCK_GUTS_NONE;
	}
	if (Mock.msg_terminate_transport_IgnoreBool) {
		Mock.msg_terminate_transport_CallInstance = CMOCK_GUTS_NONE;
	}
	UNITY_SET_DETAIL(CMockString_msg_terminate_transport);
	UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.msg_terminate_transport_CallInstance, cmock_line, CMockStringCalledLess);
	if (Mock.msg_terminate_transport_CallbackFunctionPointer != NULL) {
		Mock.msg_terminate_transport_CallInstance = CMOCK_GUTS_NONE;
	}
	if (Mock.msg_send_unicast_packet_IgnoreBool) {
		Mock.msg_send_unicast_packet_CallInstance = CMOCK_GUTS_NONE;
	}
	UNITY_SET_DETAIL(CMockString_msg_send_unicast_packet);
	UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.msg_send_unicast_packet_CallInstance, cmock_line, CMockStringCalledLess);
	if (Mock.msg_send_unicast_packet_CallbackFunctionPointer != NULL) {
		Mock.msg_send_unicast_packet_CallInstance = CMOCK_GUTS_NONE;
	}
	if (Mock.msg_send_multicast_packet_IgnoreBool) {
		Mock.msg_send_multicast_packet_CallInstance = CMOCK_GUTS_NONE;
	}
	UNITY_SET_DETAIL(CMockString_msg_send_multicast_packet);
	UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.msg_send_multicast_packet_CallInstance, cmock_line, CMockStringCalledLess);
	if (Mock.msg_send_multicast_packet_CallbackFunctionPointer != NULL) {
		Mock.msg_send_multicast_packet_CallInstance = CMOCK_GUTS_NONE;
	}
	if (Mock.msg_set_receive_handler_IgnoreBool) {
		Mock.msg_set_receive_handler_CallInstance = CMOCK_GUTS_NONE;
	}
	UNITY_SET_DETAIL(CMockString_msg_set_receive_handler);
	UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.msg_set_receive_handler_CallInstance, cmock_line, CMockStringCalledLess);
	if (Mock.msg_set_receive_handler_CallbackFunctionPointer != NULL) {
		Mock.msg_set_receive_handler_CallInstance = CMOCK_GUTS_NONE;
	}
	if (Mock.msg_unset_receive_handler_IgnoreBool) {
		Mock.msg_unset_receive_handler_CallInstance = CMOCK_GUTS_NONE;
	}
	UNITY_SET_DETAIL(CMockString_msg_unset_receive_handler);
	UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.msg_unset_receive_handler_CallInstance, cmock_line, CMockStringCalledLess);
	if (Mock.msg_unset_receive_handler_CallbackFunctionPointer != NULL) {
		Mock.msg_unset_receive_handler_CallInstance = CMOCK_GUTS_NONE;
	}
}

void Mockrt_transport_Init(void)
{
	Mockrt_transport_Destroy();
}

void Mockrt_transport_Destroy(void)
{
	CMock_Guts_MemFreeAll();
	memset(&Mock, 0, sizeof(Mock));
	Mock.msg_initialize_transport_CallbackFunctionPointer = NULL;
	Mock.msg_initialize_transport_CallbackCalls = 0;
	Mock.msg_terminate_transport_CallbackFunctionPointer = NULL;
	Mock.msg_terminate_transport_CallbackCalls = 0;
	Mock.msg_send_unicast_packet_CallbackFunctionPointer = NULL;
	Mock.msg_send_unicast_packet_CallbackCalls = 0;
	Mock.msg_send_multicast_packet_CallbackFunctionPointer = NULL;
	Mock.msg_send_multicast_packet_CallbackCalls = 0;
	Mock.msg_set_receive_handler_CallbackFunctionPointer = NULL;
	Mock.msg_set_receive_handler_CallbackCalls = 0;
	Mock.msg_unset_receive_handler_CallbackFunctionPointer = NULL;
	Mock.msg_unset_receive_handler_CallbackCalls = 0;
}

int msg_initialize_transport(void)
{
	UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
	CMOCK_msg_initialize_transport_CALL_INSTANCE *cmock_call_instance;
	UNITY_SET_DETAIL(CMockString_msg_initialize_transport);
	cmock_call_instance = (CMOCK_msg_initialize_transport_CALL_INSTANCE *) CMock_Guts_GetAddressFor(Mock.msg_initialize_transport_CallInstance);
	Mock.msg_initialize_transport_CallInstance = CMock_Guts_MemNext(Mock.msg_initialize_transport_CallInstance);
	if (Mock.msg_initialize_transport_IgnoreBool) {
		UNITY_CLR_DETAILS();
		if (cmock_call_instance == NULL) {
			return Mock.msg_initialize_transport_FinalReturn;
		}
		Mock.msg_initialize_transport_FinalReturn = cmock_call_instance->ReturnVal;
		return cmock_call_instance->ReturnVal;
	}
	if (Mock.msg_initialize_transport_CallbackFunctionPointer != NULL) {
		return Mock.msg_initialize_transport_CallbackFunctionPointer(Mock.msg_initialize_transport_CallbackCalls++);
	}
	UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
	cmock_line = cmock_call_instance->LineNumber;
	UNITY_CLR_DETAILS();
	return cmock_call_instance->ReturnVal;
}

void msg_initialize_transport_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
	CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_msg_initialize_transport_CALL_INSTANCE));
	CMOCK_msg_initialize_transport_CALL_INSTANCE *cmock_call_instance = (CMOCK_msg_initialize_transport_CALL_INSTANCE *) CMock_Guts_GetAddressFor(cmock_guts_index);
	UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
	memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
	Mock.msg_initialize_transport_CallInstance = CMock_Guts_MemChain(Mock.msg_initialize_transport_CallInstance, cmock_guts_index);
	Mock.msg_initialize_transport_IgnoreBool = (int)0;
	cmock_call_instance->LineNumber = cmock_line;
	cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
	cmock_call_instance->ReturnVal = cmock_to_return;
	Mock.msg_initialize_transport_IgnoreBool = (int)1;
}

void msg_initialize_transport_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
	CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_msg_initialize_transport_CALL_INSTANCE));
	CMOCK_msg_initialize_transport_CALL_INSTANCE *cmock_call_instance = (CMOCK_msg_initialize_transport_CALL_INSTANCE *) CMock_Guts_GetAddressFor(cmock_guts_index);
	UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
	memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
	Mock.msg_initialize_transport_CallInstance = CMock_Guts_MemChain(Mock.msg_initialize_transport_CallInstance, cmock_guts_index);
	Mock.msg_initialize_transport_IgnoreBool = (int)0;
	cmock_call_instance->LineNumber = cmock_line;
	cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
	cmock_call_instance->ReturnVal = cmock_to_return;
	cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void msg_initialize_transport_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
	CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_msg_initialize_transport_CALL_INSTANCE));
	CMOCK_msg_initialize_transport_CALL_INSTANCE *cmock_call_instance = (CMOCK_msg_initialize_transport_CALL_INSTANCE *) CMock_Guts_GetAddressFor(cmock_guts_index);
	UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
	memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
	Mock.msg_initialize_transport_CallInstance = CMock_Guts_MemChain(Mock.msg_initialize_transport_CallInstance, cmock_guts_index);
	Mock.msg_initialize_transport_IgnoreBool = (int)0;
	cmock_call_instance->LineNumber = cmock_line;
	cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
	cmock_call_instance->ReturnVal = cmock_to_return;
	UNITY_CLR_DETAILS();
}

void msg_initialize_transport_StubWithCallback(CMOCK_msg_initialize_transport_CALLBACK Callback)
{
	Mock.msg_initialize_transport_IgnoreBool = (int)0;
	Mock.msg_initialize_transport_CallbackFunctionPointer = Callback;
}

void msg_terminate_transport(void)
{
	UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
	CMOCK_msg_terminate_transport_CALL_INSTANCE *cmock_call_instance;
	UNITY_SET_DETAIL(CMockString_msg_terminate_transport);
	cmock_call_instance = (CMOCK_msg_terminate_transport_CALL_INSTANCE *) CMock_Guts_GetAddressFor(Mock.msg_terminate_transport_CallInstance);
	Mock.msg_terminate_transport_CallInstance = CMock_Guts_MemNext(Mock.msg_terminate_transport_CallInstance);
	if (Mock.msg_terminate_transport_IgnoreBool) {
		UNITY_CLR_DETAILS();
		return;
	}
	if (Mock.msg_terminate_transport_CallbackFunctionPointer != NULL) {
		Mock.msg_terminate_transport_CallbackFunctionPointer(Mock.msg_terminate_transport_CallbackCalls++);
		return;
	}
	UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
	cmock_line = cmock_call_instance->LineNumber;
	UNITY_CLR_DETAILS();
}

void msg_terminate_transport_CMockIgnore(void)
{
	Mock.msg_terminate_transport_IgnoreBool = (int)1;
}

void msg_terminate_transport_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
	CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_msg_terminate_transport_CALL_INSTANCE));
	CMOCK_msg_terminate_transport_CALL_INSTANCE *cmock_call_instance = (CMOCK_msg_terminate_transport_CALL_INSTANCE *) CMock_Guts_GetAddressFor(cmock_guts_index);
	UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
	memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
	Mock.msg_terminate_transport_CallInstance = CMock_Guts_MemChain(Mock.msg_terminate_transport_CallInstance, cmock_guts_index);
	Mock.msg_terminate_transport_IgnoreBool = (int)0;
	cmock_call_instance->LineNumber = cmock_line;
	cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
	cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void msg_terminate_transport_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
	CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_msg_terminate_transport_CALL_INSTANCE));
	CMOCK_msg_terminate_transport_CALL_INSTANCE *cmock_call_instance = (CMOCK_msg_terminate_transport_CALL_INSTANCE *) CMock_Guts_GetAddressFor(cmock_guts_index);
	UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
	memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
	Mock.msg_terminate_transport_CallInstance = CMock_Guts_MemChain(Mock.msg_terminate_transport_CallInstance, cmock_guts_index);
	Mock.msg_terminate_transport_IgnoreBool = (int)0;
	cmock_call_instance->LineNumber = cmock_line;
	cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
	UNITY_CLR_DETAILS();
}

void msg_terminate_transport_StubWithCallback(CMOCK_msg_terminate_transport_CALLBACK Callback)
{
	Mock.msg_terminate_transport_IgnoreBool = (int)0;
	Mock.msg_terminate_transport_CallbackFunctionPointer = Callback;
}

void msg_send_unicast_packet(const uint8_t *packet, uint16_t len, const ocf_endpoint_s *endpoint)
{
	UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
	CMOCK_msg_send_unicast_packet_CALL_INSTANCE *cmock_call_instance;
	UNITY_SET_DETAIL(CMockString_msg_send_unicast_packet);
	cmock_call_instance = (CMOCK_msg_send_unicast_packet_CALL_INSTANCE *) CMock_Guts_GetAddressFor(Mock.msg_send_unicast_packet_CallInstance);
	Mock.msg_send_unicast_packet_CallInstance = CMock_Guts_MemNext(Mock.msg_send_unicast_packet_CallInstance);
	if (Mock.msg_send_unicast_packet_IgnoreBool) {
		UNITY_CLR_DETAILS();
		return;
	}
	if (Mock.msg_send_unicast_packet_CallbackFunctionPointer != NULL) {
		Mock.msg_send_unicast_packet_CallbackFunctionPointer(packet, len, endpoint, Mock.msg_send_unicast_packet_CallbackCalls++);
		return;
	}
	UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
	cmock_line = cmock_call_instance->LineNumber;
	if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE) {
		if (!cmock_call_instance->IgnoreArg_packet) {
			UNITY_SET_DETAILS(CMockString_msg_send_unicast_packet, CMockString_packet);
			if (cmock_call_instance->Expected_packet == NULL) {
				UNITY_TEST_ASSERT_NULL(packet, cmock_line, CMockStringExpNULL);
			} else {
				UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_packet, packet, 1, cmock_line, CMockStringMismatch);
			}
		}
		if (!cmock_call_instance->IgnoreArg_len) {
			UNITY_SET_DETAILS(CMockString_msg_send_unicast_packet, CMockString_len);
			UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_len, len, cmock_line, CMockStringMismatch);
		}
		if (!cmock_call_instance->IgnoreArg_endpoint) {
			UNITY_SET_DETAILS(CMockString_msg_send_unicast_packet, CMockString_endpoint);
			UNITY_TEST_ASSERT_EQUAL_MEMORY((void *)(cmock_call_instance->Expected_endpoint), (void *)(endpoint), sizeof(ocf_endpoint_s), cmock_line, CMockStringMismatch);
		}

	}
	UNITY_CLR_DETAILS();
}

void CMockExpectParameters_msg_send_unicast_packet(CMOCK_msg_send_unicast_packet_CALL_INSTANCE *cmock_call_instance, const uint8_t *packet, uint16_t len, const ocf_endpoint_s *endpoint)
{
	cmock_call_instance->Expected_packet = (uint8_t *) packet;
	cmock_call_instance->IgnoreArg_packet = 0;
	cmock_call_instance->Expected_len = len;
	cmock_call_instance->IgnoreArg_len = 0;
	cmock_call_instance->Expected_endpoint = (ocf_endpoint_s *) endpoint;
	cmock_call_instance->IgnoreArg_endpoint = 0;
}

void msg_send_unicast_packet_CMockIgnore(void)
{
	Mock.msg_send_unicast_packet_IgnoreBool = (int)1;
}

void msg_send_unicast_packet_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
	CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_msg_send_unicast_packet_CALL_INSTANCE));
	CMOCK_msg_send_unicast_packet_CALL_INSTANCE *cmock_call_instance = (CMOCK_msg_send_unicast_packet_CALL_INSTANCE *) CMock_Guts_GetAddressFor(cmock_guts_index);
	UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
	memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
	Mock.msg_send_unicast_packet_CallInstance = CMock_Guts_MemChain(Mock.msg_send_unicast_packet_CallInstance, cmock_guts_index);
	Mock.msg_send_unicast_packet_IgnoreBool = (int)0;
	cmock_call_instance->LineNumber = cmock_line;
	cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
	cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void msg_send_unicast_packet_CMockExpect(UNITY_LINE_TYPE cmock_line, const uint8_t *packet, uint16_t len, const ocf_endpoint_s *endpoint)
{
	CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_msg_send_unicast_packet_CALL_INSTANCE));
	CMOCK_msg_send_unicast_packet_CALL_INSTANCE *cmock_call_instance = (CMOCK_msg_send_unicast_packet_CALL_INSTANCE *) CMock_Guts_GetAddressFor(cmock_guts_index);
	UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
	memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
	Mock.msg_send_unicast_packet_CallInstance = CMock_Guts_MemChain(Mock.msg_send_unicast_packet_CallInstance, cmock_guts_index);
	Mock.msg_send_unicast_packet_IgnoreBool = (int)0;
	cmock_call_instance->LineNumber = cmock_line;
	cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
	CMockExpectParameters_msg_send_unicast_packet(cmock_call_instance, packet, len, endpoint);
	UNITY_CLR_DETAILS();
}

void msg_send_unicast_packet_StubWithCallback(CMOCK_msg_send_unicast_packet_CALLBACK Callback)
{
	Mock.msg_send_unicast_packet_IgnoreBool = (int)0;
	Mock.msg_send_unicast_packet_CallbackFunctionPointer = Callback;
}

void msg_send_unicast_packet_CMockIgnoreArg_packet(UNITY_LINE_TYPE cmock_line)
{
	CMOCK_msg_send_unicast_packet_CALL_INSTANCE *cmock_call_instance = (CMOCK_msg_send_unicast_packet_CALL_INSTANCE *) CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.msg_send_unicast_packet_CallInstance));
	UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
	cmock_call_instance->IgnoreArg_packet = 1;
}

void msg_send_unicast_packet_CMockIgnoreArg_len(UNITY_LINE_TYPE cmock_line)
{
	CMOCK_msg_send_unicast_packet_CALL_INSTANCE *cmock_call_instance = (CMOCK_msg_send_unicast_packet_CALL_INSTANCE *) CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.msg_send_unicast_packet_CallInstance));
	UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
	cmock_call_instance->IgnoreArg_len = 1;
}

void msg_send_unicast_packet_CMockIgnoreArg_endpoint(UNITY_LINE_TYPE cmock_line)
{
	CMOCK_msg_send_unicast_packet_CALL_INSTANCE *cmock_call_instance = (CMOCK_msg_send_unicast_packet_CALL_INSTANCE *) CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.msg_send_unicast_packet_CallInstance));
	UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
	cmock_call_instance->IgnoreArg_endpoint = 1;
}

void msg_send_multicast_packet(const uint8_t *packet, uint16_t len)
{
	UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
	CMOCK_msg_send_multicast_packet_CALL_INSTANCE *cmock_call_instance;
	UNITY_SET_DETAIL(CMockString_msg_send_multicast_packet);
	cmock_call_instance = (CMOCK_msg_send_multicast_packet_CALL_INSTANCE *) CMock_Guts_GetAddressFor(Mock.msg_send_multicast_packet_CallInstance);
	Mock.msg_send_multicast_packet_CallInstance = CMock_Guts_MemNext(Mock.msg_send_multicast_packet_CallInstance);
	if (Mock.msg_send_multicast_packet_IgnoreBool) {
		UNITY_CLR_DETAILS();
		return;
	}
	if (Mock.msg_send_multicast_packet_CallbackFunctionPointer != NULL) {
		Mock.msg_send_multicast_packet_CallbackFunctionPointer(packet, len, Mock.msg_send_multicast_packet_CallbackCalls++);
		return;
	}
	UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
	cmock_line = cmock_call_instance->LineNumber;
	if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE) {
		if (!cmock_call_instance->IgnoreArg_packet) {
			UNITY_SET_DETAILS(CMockString_msg_send_multicast_packet, CMockString_packet);
			if (cmock_call_instance->Expected_packet == NULL) {
				UNITY_TEST_ASSERT_NULL(packet, cmock_line, CMockStringExpNULL);
			} else {
				UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_packet, packet, 1, cmock_line, CMockStringMismatch);
			}
		}
		if (!cmock_call_instance->IgnoreArg_len) {
			UNITY_SET_DETAILS(CMockString_msg_send_multicast_packet, CMockString_len);
			UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_len, len, cmock_line, CMockStringMismatch);
		}

	}
	UNITY_CLR_DETAILS();
}

void CMockExpectParameters_msg_send_multicast_packet(CMOCK_msg_send_multicast_packet_CALL_INSTANCE *cmock_call_instance, const uint8_t *packet, uint16_t len)
{
	cmock_call_instance->Expected_packet = (uint8_t *) packet;
	cmock_call_instance->IgnoreArg_packet = 0;
	cmock_call_instance->Expected_len = len;
	cmock_call_instance->IgnoreArg_len = 0;
}

void msg_send_multicast_packet_CMockIgnore(void)
{
	Mock.msg_send_multicast_packet_IgnoreBool = (int)1;
}

void msg_send_multicast_packet_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
	CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_msg_send_multicast_packet_CALL_INSTANCE));
	CMOCK_msg_send_multicast_packet_CALL_INSTANCE *cmock_call_instance = (CMOCK_msg_send_multicast_packet_CALL_INSTANCE *) CMock_Guts_GetAddressFor(cmock_guts_index);
	UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
	memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
	Mock.msg_send_multicast_packet_CallInstance = CMock_Guts_MemChain(Mock.msg_send_multicast_packet_CallInstance, cmock_guts_index);
	Mock.msg_send_multicast_packet_IgnoreBool = (int)0;
	cmock_call_instance->LineNumber = cmock_line;
	cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
	cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void msg_send_multicast_packet_CMockExpect(UNITY_LINE_TYPE cmock_line, const uint8_t *packet, uint16_t len)
{
	CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_msg_send_multicast_packet_CALL_INSTANCE));
	CMOCK_msg_send_multicast_packet_CALL_INSTANCE *cmock_call_instance = (CMOCK_msg_send_multicast_packet_CALL_INSTANCE *) CMock_Guts_GetAddressFor(cmock_guts_index);
	UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
	memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
	Mock.msg_send_multicast_packet_CallInstance = CMock_Guts_MemChain(Mock.msg_send_multicast_packet_CallInstance, cmock_guts_index);
	Mock.msg_send_multicast_packet_IgnoreBool = (int)0;
	cmock_call_instance->LineNumber = cmock_line;
	cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
	CMockExpectParameters_msg_send_multicast_packet(cmock_call_instance, packet, len);
	UNITY_CLR_DETAILS();
}

void msg_send_multicast_packet_StubWithCallback(CMOCK_msg_send_multicast_packet_CALLBACK Callback)
{
	Mock.msg_send_multicast_packet_IgnoreBool = (int)0;
	Mock.msg_send_multicast_packet_CallbackFunctionPointer = Callback;
}

void msg_send_multicast_packet_CMockIgnoreArg_packet(UNITY_LINE_TYPE cmock_line)
{
	CMOCK_msg_send_multicast_packet_CALL_INSTANCE *cmock_call_instance = (CMOCK_msg_send_multicast_packet_CALL_INSTANCE *) CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.msg_send_multicast_packet_CallInstance));
	UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
	cmock_call_instance->IgnoreArg_packet = 1;
}

void msg_send_multicast_packet_CMockIgnoreArg_len(UNITY_LINE_TYPE cmock_line)
{
	CMOCK_msg_send_multicast_packet_CALL_INSTANCE *cmock_call_instance = (CMOCK_msg_send_multicast_packet_CALL_INSTANCE *) CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.msg_send_multicast_packet_CallInstance));
	UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
	cmock_call_instance->IgnoreArg_len = 1;
}

int msg_set_receive_handler(msg_receive_handler recv_handler)
{
	UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
	CMOCK_msg_set_receive_handler_CALL_INSTANCE *cmock_call_instance;
	UNITY_SET_DETAIL(CMockString_msg_set_receive_handler);
	cmock_call_instance = (CMOCK_msg_set_receive_handler_CALL_INSTANCE *) CMock_Guts_GetAddressFor(Mock.msg_set_receive_handler_CallInstance);
	Mock.msg_set_receive_handler_CallInstance = CMock_Guts_MemNext(Mock.msg_set_receive_handler_CallInstance);
	if (Mock.msg_set_receive_handler_IgnoreBool) {
		UNITY_CLR_DETAILS();
		if (cmock_call_instance == NULL) {
			return Mock.msg_set_receive_handler_FinalReturn;
		}
		Mock.msg_set_receive_handler_FinalReturn = cmock_call_instance->ReturnVal;
		return cmock_call_instance->ReturnVal;
	}
	if (Mock.msg_set_receive_handler_CallbackFunctionPointer != NULL) {
		return Mock.msg_set_receive_handler_CallbackFunctionPointer(recv_handler, Mock.msg_set_receive_handler_CallbackCalls++);
	}
	UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
	cmock_line = cmock_call_instance->LineNumber;
	if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE) {
		if (!cmock_call_instance->IgnoreArg_recv_handler) {
			UNITY_SET_DETAILS(CMockString_msg_set_receive_handler, CMockString_recv_handler);
			UNITY_TEST_ASSERT_EQUAL_MEMORY((void *)(&cmock_call_instance->Expected_recv_handler), (void *)(&recv_handler), sizeof(msg_receive_handler), cmock_line, CMockStringMismatch);
		}

	}
	UNITY_CLR_DETAILS();
	return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_msg_set_receive_handler(CMOCK_msg_set_receive_handler_CALL_INSTANCE *cmock_call_instance, msg_receive_handler recv_handler)
{
	memcpy(&cmock_call_instance->Expected_recv_handler, &recv_handler, sizeof(msg_receive_handler));
	cmock_call_instance->IgnoreArg_recv_handler = 0;
}

void msg_set_receive_handler_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
	CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_msg_set_receive_handler_CALL_INSTANCE));
	CMOCK_msg_set_receive_handler_CALL_INSTANCE *cmock_call_instance = (CMOCK_msg_set_receive_handler_CALL_INSTANCE *) CMock_Guts_GetAddressFor(cmock_guts_index);
	UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
	memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
	Mock.msg_set_receive_handler_CallInstance = CMock_Guts_MemChain(Mock.msg_set_receive_handler_CallInstance, cmock_guts_index);
	Mock.msg_set_receive_handler_IgnoreBool = (int)0;
	cmock_call_instance->LineNumber = cmock_line;
	cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
	cmock_call_instance->ReturnVal = cmock_to_return;
	Mock.msg_set_receive_handler_IgnoreBool = (int)1;
}

void msg_set_receive_handler_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
	CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_msg_set_receive_handler_CALL_INSTANCE));
	CMOCK_msg_set_receive_handler_CALL_INSTANCE *cmock_call_instance = (CMOCK_msg_set_receive_handler_CALL_INSTANCE *) CMock_Guts_GetAddressFor(cmock_guts_index);
	UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
	memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
	Mock.msg_set_receive_handler_CallInstance = CMock_Guts_MemChain(Mock.msg_set_receive_handler_CallInstance, cmock_guts_index);
	Mock.msg_set_receive_handler_IgnoreBool = (int)0;
	cmock_call_instance->LineNumber = cmock_line;
	cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
	cmock_call_instance->ReturnVal = cmock_to_return;
	cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void msg_set_receive_handler_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, msg_receive_handler recv_handler, int cmock_to_return)
{
	CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_msg_set_receive_handler_CALL_INSTANCE));
	CMOCK_msg_set_receive_handler_CALL_INSTANCE *cmock_call_instance = (CMOCK_msg_set_receive_handler_CALL_INSTANCE *) CMock_Guts_GetAddressFor(cmock_guts_index);
	UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
	memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
	Mock.msg_set_receive_handler_CallInstance = CMock_Guts_MemChain(Mock.msg_set_receive_handler_CallInstance, cmock_guts_index);
	Mock.msg_set_receive_handler_IgnoreBool = (int)0;
	cmock_call_instance->LineNumber = cmock_line;
	cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
	CMockExpectParameters_msg_set_receive_handler(cmock_call_instance, recv_handler);
	cmock_call_instance->ReturnVal = cmock_to_return;
	UNITY_CLR_DETAILS();
}

void msg_set_receive_handler_StubWithCallback(CMOCK_msg_set_receive_handler_CALLBACK Callback)
{
	Mock.msg_set_receive_handler_IgnoreBool = (int)0;
	Mock.msg_set_receive_handler_CallbackFunctionPointer = Callback;
}

void msg_set_receive_handler_CMockIgnoreArg_recv_handler(UNITY_LINE_TYPE cmock_line)
{
	CMOCK_msg_set_receive_handler_CALL_INSTANCE *cmock_call_instance = (CMOCK_msg_set_receive_handler_CALL_INSTANCE *) CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.msg_set_receive_handler_CallInstance));
	UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
	cmock_call_instance->IgnoreArg_recv_handler = 1;
}

int msg_unset_receive_handler(void)
{
	UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
	CMOCK_msg_unset_receive_handler_CALL_INSTANCE *cmock_call_instance;
	UNITY_SET_DETAIL(CMockString_msg_unset_receive_handler);
	cmock_call_instance = (CMOCK_msg_unset_receive_handler_CALL_INSTANCE *) CMock_Guts_GetAddressFor(Mock.msg_unset_receive_handler_CallInstance);
	Mock.msg_unset_receive_handler_CallInstance = CMock_Guts_MemNext(Mock.msg_unset_receive_handler_CallInstance);
	if (Mock.msg_unset_receive_handler_IgnoreBool) {
		UNITY_CLR_DETAILS();
		if (cmock_call_instance == NULL) {
			return Mock.msg_unset_receive_handler_FinalReturn;
		}
		Mock.msg_unset_receive_handler_FinalReturn = cmock_call_instance->ReturnVal;
		return cmock_call_instance->ReturnVal;
	}
	if (Mock.msg_unset_receive_handler_CallbackFunctionPointer != NULL) {
		return Mock.msg_unset_receive_handler_CallbackFunctionPointer(Mock.msg_unset_receive_handler_CallbackCalls++);
	}
	UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
	cmock_line = cmock_call_instance->LineNumber;
	UNITY_CLR_DETAILS();
	return cmock_call_instance->ReturnVal;
}

void msg_unset_receive_handler_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
	CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_msg_unset_receive_handler_CALL_INSTANCE));
	CMOCK_msg_unset_receive_handler_CALL_INSTANCE *cmock_call_instance = (CMOCK_msg_unset_receive_handler_CALL_INSTANCE *) CMock_Guts_GetAddressFor(cmock_guts_index);
	UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
	memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
	Mock.msg_unset_receive_handler_CallInstance = CMock_Guts_MemChain(Mock.msg_unset_receive_handler_CallInstance, cmock_guts_index);
	Mock.msg_unset_receive_handler_IgnoreBool = (int)0;
	cmock_call_instance->LineNumber = cmock_line;
	cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
	cmock_call_instance->ReturnVal = cmock_to_return;
	Mock.msg_unset_receive_handler_IgnoreBool = (int)1;
}

void msg_unset_receive_handler_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
	CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_msg_unset_receive_handler_CALL_INSTANCE));
	CMOCK_msg_unset_receive_handler_CALL_INSTANCE *cmock_call_instance = (CMOCK_msg_unset_receive_handler_CALL_INSTANCE *) CMock_Guts_GetAddressFor(cmock_guts_index);
	UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
	memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
	Mock.msg_unset_receive_handler_CallInstance = CMock_Guts_MemChain(Mock.msg_unset_receive_handler_CallInstance, cmock_guts_index);
	Mock.msg_unset_receive_handler_IgnoreBool = (int)0;
	cmock_call_instance->LineNumber = cmock_line;
	cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
	cmock_call_instance->ReturnVal = cmock_to_return;
	cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void msg_unset_receive_handler_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
	CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_msg_unset_receive_handler_CALL_INSTANCE));
	CMOCK_msg_unset_receive_handler_CALL_INSTANCE *cmock_call_instance = (CMOCK_msg_unset_receive_handler_CALL_INSTANCE *) CMock_Guts_GetAddressFor(cmock_guts_index);
	UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
	memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
	Mock.msg_unset_receive_handler_CallInstance = CMock_Guts_MemChain(Mock.msg_unset_receive_handler_CallInstance, cmock_guts_index);
	Mock.msg_unset_receive_handler_IgnoreBool = (int)0;
	cmock_call_instance->LineNumber = cmock_line;
	cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
	cmock_call_instance->ReturnVal = cmock_to_return;
	UNITY_CLR_DETAILS();
}

void msg_unset_receive_handler_StubWithCallback(CMOCK_msg_unset_receive_handler_CALLBACK Callback)
{
	Mock.msg_unset_receive_handler_IgnoreBool = (int)0;
	Mock.msg_unset_receive_handler_CallbackFunctionPointer = Callback;
}
